IF SCHEMA_ID(N'flight') IS NULL EXEC(N'CREATE SCHEMA flight;');

IF SCHEMA_ID(N'hotels') IS NULL EXEC(N'CREATE SCHEMA hotels;');

IF SCHEMA_ID(N'fleet') IS NULL EXEC(N'CREATE SCHEMA fleet;');

IF SCHEMA_ID(N'geo') IS NULL EXEC(N'CREATE SCHEMA geo;');

IF SCHEMA_ID(N'catalog') IS NULL EXEC(N'CREATE SCHEMA catalog;');

IF SCHEMA_ID(N'cms') IS NULL EXEC(N'CREATE SCHEMA cms;');

IF SCHEMA_ID(N'auth') IS NULL EXEC(N'CREATE SCHEMA auth;');

IF SCHEMA_ID(N'bus') IS NULL EXEC(N'CREATE SCHEMA bus;');

IF SCHEMA_ID(N'train') IS NULL EXEC(N'CREATE SCHEMA train;');

IF SCHEMA_ID(N'tenants') IS NULL EXEC(N'CREATE SCHEMA tenants;');

IF SCHEMA_ID(N'tours') IS NULL EXEC(N'CREATE SCHEMA tours;');

CREATE TABLE flight.AircraftModels (
    Id uuid NOT NULL DEFAULT (NEWSEQUENTIALID()),
    TenantId uuid NOT NULL,
    Code varchar(50) NOT NULL,
    Manufacturer varchar(100) NOT NULL,
    Model varchar(100) NOT NULL,
    TypicalSeatCapacity int NULL,
    MetadataJson text NULL,
    IsActive boolean NOT NULL DEFAULT CAST(1 AS boolean),
    IsDeleted boolean NOT NULL DEFAULT CAST(0 AS boolean),
    CreatedAt datetime NOT NULL DEFAULT (SWITCHOFFSET(SYSDATETIMEOFFSET(), '+07:00')),
    CreatedByUserId uuid NULL,
    UpdatedAt datetime NULL,
    UpdatedByUserId uuid NULL,
    varbinary(8) varbinary(8) NOT NULL,
    CONSTRAINT PK_AircraftModels PRIMARY KEY (Id)
);

CREATE TABLE flight.Airlines (
    Id uuid NOT NULL DEFAULT (NEWSEQUENTIALID()),
    TenantId uuid NOT NULL,
    Code varchar(50) NOT NULL,
    Name varchar(200) NOT NULL,
    IataCode varchar(8) NULL,
    IcaoCode varchar(8) NULL,
    LogoUrl varchar(1000) NULL,
    WebsiteUrl varchar(1000) NULL,
    SupportPhone varchar(50) NULL,
    SupportEmail varchar(200) NULL,
    IsActive boolean NOT NULL DEFAULT CAST(1 AS boolean),
    IsDeleted boolean NOT NULL DEFAULT CAST(0 AS boolean),
    CreatedAt datetime NOT NULL DEFAULT (SWITCHOFFSET(SYSDATETIMEOFFSET(), '+07:00')),
    CreatedByUserId uuid NULL,
    UpdatedAt datetime NULL,
    UpdatedByUserId uuid NULL,
    varbinary(8) varbinary(8) NOT NULL,
    CONSTRAINT PK_Airlines PRIMARY KEY (Id)
);

CREATE TABLE AspNetRoles (
    Id uuid NOT NULL,
    Name varchar(256) NULL,
    NormalizedName varchar(256) NULL,
    ConcurrencyStamp text NULL,
    CONSTRAINT PK_AspNetRoles PRIMARY KEY (Id)
);

CREATE TABLE AspNetUsers (
    Id uuid NOT NULL,
    FullName varchar(200) NULL,
    IsActive boolean NOT NULL DEFAULT CAST(1 AS boolean),
    AvatarUrl varchar(500) NULL,
    CreatedAt datetime NOT NULL,
    UpdatedAt datetime NULL,
    UserName varchar(256) NULL,
    NormalizedUserName varchar(256) NULL,
    Email varchar(256) NULL,
    NormalizedEmail varchar(256) NULL,
    EmailConfirmed boolean NOT NULL,
    PasswordHash text NULL,
    SecurityStamp text NULL,
    ConcurrencyStamp text NULL,
    PhoneNumber text NULL,
    PhoneNumberConfirmed boolean NOT NULL,
    TwoFactorEnabled boolean NOT NULL,
    LockoutEnd datetime NULL,
    LockoutEnabled boolean NOT NULL,
    AccessFailedCount int NOT NULL,
    CONSTRAINT PK_AspNetUsers PRIMARY KEY (Id)
);

CREATE TABLE hotels.BedTypes (
    Id uuid NOT NULL,
    TenantId uuid NOT NULL,
    Code varchar(50) NOT NULL,
    Name varchar(200) NOT NULL,
    Description varchar(2000) NULL,
    IsActive boolean NOT NULL,
    IsDeleted boolean NOT NULL,
    CreatedAt datetime NOT NULL,
    CreatedByUserId uuid NULL,
    UpdatedAt datetime NULL,
    UpdatedByUserId uuid NULL,
    varbinary(8) varbinary(8) NOT NULL,
    CONSTRAINT PK_BedTypes PRIMARY KEY (Id)
);

CREATE TABLE geo.GeoSyncLogs (
    Id uuid NOT NULL,
    Source varchar(100) NOT NULL,
    Url varchar(500) NOT NULL,
    Depth int NOT NULL,
    IsSuccess boolean NOT NULL,
    HttpStatus int NOT NULL,
    ProvincesInserted int NOT NULL,
    ProvincesUpdated int NOT NULL,
    DistrictsInserted int NOT NULL,
    DistrictsUpdated int NOT NULL,
    WardsInserted int NOT NULL,
    WardsUpdated int NOT NULL,
    ErrorMessage varchar(1000) NULL,
    ErrorDetail text NULL,
    CreatedAt datetime NOT NULL,
    CONSTRAINT PK_GeoSyncLogs PRIMARY KEY (Id)
);

CREATE TABLE hotels.HotelAmenities (
    Id uuid NOT NULL,
    TenantId uuid NOT NULL,
    Scope int NOT NULL,
    Kind int NOT NULL,
    Code varchar(80) NOT NULL,
    Name varchar(200) NOT NULL,
    Description varchar(2000) NULL,
    SortOrder int NOT NULL,
    IconKey varchar(200) NULL,
    MetadataJson text NULL,
    IsActive boolean NOT NULL,
    IsDeleted boolean NOT NULL,
    CreatedAt datetime NOT NULL,
    CreatedByUserId uuid NULL,
    UpdatedAt datetime NULL,
    UpdatedByUserId uuid NULL,
    varbinary(8) varbinary(8) NOT NULL,
    CONSTRAINT PK_HotelAmenities PRIMARY KEY (Id)
);

CREATE TABLE hotels.Hotels (
    Id uuid NOT NULL,
    TenantId uuid NOT NULL,
    Code varchar(50) NOT NULL,
    Name varchar(300) NOT NULL,
    Slug varchar(300) NULL,
    LocationId uuid NULL,
    AddressLine varchar(500) NULL,
    City varchar(200) NULL,
    Province varchar(200) NULL,
    CountryCode varchar(10) NULL,
    Latitude decimal(9,6) NULL,
    Longitude decimal(9,6) NULL,
    TimeZone varchar(100) NULL,
    ShortDescription varchar(2000) NULL,
    DescriptionMarkdown text NULL,
    DescriptionHtml text NULL,
    StarRating int NOT NULL,
    Status int NOT NULL,
    DefaultCheckInTime time(0) NULL,
    DefaultCheckOutTime time(0) NULL,
    Phone varchar(50) NULL,
    Email varchar(200) NULL,
    WebsiteUrl varchar(1000) NULL,
    SeoTitle varchar(300) NULL,
    SeoDescription varchar(2000) NULL,
    SeoKeywords varchar(2000) NULL,
    CanonicalUrl varchar(1000) NULL,
    Robots varchar(200) NULL,
    OgImageUrl varchar(1000) NULL,
    SchemaJsonLd text NULL,
    CoverMediaAssetId uuid NULL,
    CoverImageUrl varchar(1000) NULL,
    PoliciesJson text NULL,
    MetadataJson text NULL,
    IsActive boolean NOT NULL,
    IsDeleted boolean NOT NULL,
    CreatedAt datetime NOT NULL,
    CreatedByUserId uuid NULL,
    UpdatedAt datetime NULL,
    UpdatedByUserId uuid NULL,
    varbinary(8) varbinary(8) NOT NULL,
    CONSTRAINT PK_Hotels PRIMARY KEY (Id)
);

CREATE TABLE hotels.MealPlans (
    Id uuid NOT NULL,
    TenantId uuid NOT NULL,
    Code varchar(50) NOT NULL,
    Name varchar(200) NOT NULL,
    Description varchar(2000) NULL,
    IsActive boolean NOT NULL,
    IsDeleted boolean NOT NULL,
    CreatedAt datetime NOT NULL,
    CreatedByUserId uuid NULL,
    UpdatedAt datetime NULL,
    UpdatedByUserId uuid NULL,
    varbinary(8) varbinary(8) NOT NULL,
    CONSTRAINT PK_MealPlans PRIMARY KEY (Id)
);

CREATE TABLE cms.MediaAssets (
    Id uuid NOT NULL,
    TenantId uuid NOT NULL,
    Type int NOT NULL,
    FileName varchar(255) NOT NULL,
    Title varchar(200) NULL,
    AltText varchar(300) NULL,
    StorageProvider varchar(50) NOT NULL,
    StorageKey varchar(500) NOT NULL,
    PublicUrl varchar(1000) NULL,
    MimeType varchar(100) NOT NULL,
    SizeBytes bigint NOT NULL,
    Width int NULL,
    Height int NULL,
    ChecksumSha256 varchar(128) NULL,
    MetadataJson text NULL,
    IsActive boolean NOT NULL,
    IsDeleted boolean NOT NULL,
    CreatedAt datetime NOT NULL,
    CreatedByUserId uuid NULL,
    UpdatedAt datetime NULL,
    UpdatedByUserId uuid NULL,
    varbinary(8) blob NOT NULL,
    CONSTRAINT PK_MediaAssets PRIMARY KEY (Id)
);

CREATE TABLE cms.NewsCategories (
    Id uuid NOT NULL,
    TenantId uuid NOT NULL,
    Name varchar(200) NOT NULL,
    Slug varchar(200) NOT NULL,
    Description varchar(2000) NULL,
    SortOrder int NOT NULL,
    IsActive boolean NOT NULL,
    IsDeleted boolean NOT NULL,
    CreatedAt datetime NOT NULL,
    CreatedByUserId uuid NULL,
    UpdatedAt datetime NULL,
    UpdatedByUserId uuid NULL,
    varbinary(8) blob NOT NULL,
    CONSTRAINT PK_NewsCategories PRIMARY KEY (Id)
);

CREATE TABLE cms.NewsRedirects (
    Id uuid NOT NULL,
    TenantId uuid NOT NULL,
    FromPath varchar(500) NOT NULL,
    ToPath varchar(1000) NOT NULL,
    StatusCode int NOT NULL,
    IsRegex boolean NOT NULL,
    Reason varchar(500) NULL,
    IsActive boolean NOT NULL,
    IsDeleted boolean NOT NULL,
    CreatedAt datetime NOT NULL,
    CreatedByUserId uuid NULL,
    UpdatedAt datetime NULL,
    UpdatedByUserId uuid NULL,
    varbinary(8) blob NOT NULL,
    CONSTRAINT PK_NewsRedirects PRIMARY KEY (Id)
);

CREATE TABLE cms.NewsTags (
    Id uuid NOT NULL,
    TenantId uuid NOT NULL,
    Name varchar(200) NOT NULL,
    Slug varchar(200) NOT NULL,
    IsActive boolean NOT NULL,
    IsDeleted boolean NOT NULL,
    CreatedAt datetime NOT NULL,
    CreatedByUserId uuid NULL,
    UpdatedAt datetime NULL,
    UpdatedByUserId uuid NULL,
    varbinary(8) blob NOT NULL,
    CONSTRAINT PK_NewsTags PRIMARY KEY (Id)
);

CREATE TABLE auth.Permissions (
    Id uuid NOT NULL,
    Code varchar(200) NOT NULL,
    Name varchar(200) NOT NULL,
    Description varchar(1000) NULL,
    Category varchar(100) NULL,
    SortOrder int NOT NULL DEFAULT 0,
    IsActive boolean NOT NULL DEFAULT CAST(1 AS boolean),
    IsDeleted boolean NOT NULL DEFAULT CAST(0 AS boolean),
    CreatedAt datetime NOT NULL,
    CreatedByUserId uuid NULL,
    UpdatedAt datetime NULL,
    UpdatedByUserId uuid NULL,
    varbinary(8) varbinary(8) NOT NULL,
    CONSTRAINT PK_Permissions PRIMARY KEY (Id)
);

CREATE TABLE geo.Provinces (
    Id uuid NOT NULL,
    Code int NOT NULL,
    Name varchar(200) NOT NULL,
    NameEn varchar(200) NULL,
    Slug varchar(250) NULL,
    Type varchar(50) NULL,
    RegionCode int NULL,
    IsActive boolean NOT NULL DEFAULT CAST(1 AS boolean),
    CreatedAt datetime NOT NULL,
    UpdatedAt datetime NULL,
    CONSTRAINT PK_Provinces PRIMARY KEY (Id)
);

CREATE TABLE hotels.RoomAmenities (
    Id uuid NOT NULL,
    TenantId uuid NOT NULL,
    Kind int NOT NULL,
    Code varchar(80) NOT NULL,
    Name varchar(200) NOT NULL,
    Description varchar(2000) NULL,
    SortOrder int NOT NULL,
    IconKey varchar(200) NULL,
    MetadataJson text NULL,
    IsActive boolean NOT NULL,
    IsDeleted boolean NOT NULL,
    CreatedAt datetime NOT NULL,
    CreatedByUserId uuid NULL,
    UpdatedAt datetime NULL,
    UpdatedByUserId uuid NULL,
    varbinary(8) varbinary(8) NOT NULL,
    CONSTRAINT PK_RoomAmenities PRIMARY KEY (Id)
);

CREATE TABLE fleet.SeatMaps (
    Id uuid NOT NULL,
    TenantId uuid NOT NULL,
    VehicleType int NOT NULL,
    Code varchar(50) NOT NULL,
    Name varchar(200) NOT NULL,
    TotalRows int NOT NULL,
    TotalColumns int NOT NULL,
    DeckCount int NOT NULL DEFAULT 1,
    LayoutVersion varchar(50) NULL,
    SeatLabelScheme varchar(50) NULL,
    IsActive boolean NOT NULL DEFAULT CAST(1 AS boolean),
    MetadataJson text NULL,
    IsDeleted boolean NOT NULL DEFAULT CAST(0 AS boolean),
    CreatedAt datetime NOT NULL,
    CreatedByUserId uuid NULL,
    UpdatedAt datetime NULL,
    UpdatedByUserId uuid NULL,
    varbinary(8) blob NOT NULL,
    CONSTRAINT PK_SeatMaps PRIMARY KEY (Id)
);

CREATE TABLE cms.SiteSettings (
    Id uuid NOT NULL,
    TenantId uuid NOT NULL,
    SiteName varchar(200) NOT NULL,
    SiteUrl varchar(1000) NULL,
    DefaultRobots varchar(200) NULL,
    DefaultOgImageUrl varchar(1000) NULL,
    DefaultTwitterCard varchar(50) NULL,
    DefaultTwitterSite varchar(100) NULL,
    DefaultSchemaJsonLd text NULL,
    BrandLogoUrl varchar(1000) NULL,
    SupportEmail varchar(200) NULL,
    SupportPhone varchar(50) NULL,
    IsActive boolean NOT NULL,
    IsDeleted boolean NOT NULL,
    CreatedAt datetime NOT NULL,
    CreatedByUserId uuid NULL,
    UpdatedAt datetime NULL,
    UpdatedByUserId uuid NULL,
    varbinary(8) blob NOT NULL,
    CONSTRAINT PK_SiteSettings PRIMARY KEY (Id)
);

CREATE TABLE tenants.Tenants (
    Id uuid NOT NULL,
    Code varchar(32) NOT NULL,
    Name varchar(200) NOT NULL,
    Type int NOT NULL,
    Status int NOT NULL,
    HoldMinutes int NOT NULL DEFAULT 5,
    IsDeleted boolean NOT NULL DEFAULT CAST(0 AS boolean),
    CreatedAt datetime NOT NULL,
    CreatedByUserId uuid NULL,
    UpdatedAt datetime NULL,
    UpdatedByUserId uuid NULL,
    varbinary(8) blob NOT NULL,
    CONSTRAINT PK_Tenants PRIMARY KEY (Id)
);

CREATE TABLE tours.Tours (
    Id uuid NOT NULL,
    TenantId uuid NOT NULL,
    ProviderId uuid NULL,
    PrimaryLocationId uuid NULL,
    Code varchar(50) NOT NULL,
    Name varchar(300) NOT NULL,
    Slug varchar(300) NOT NULL,
    Type int NOT NULL,
    Status int NOT NULL,
    Difficulty int NOT NULL,
    DurationDays int NOT NULL,
    DurationNights int NOT NULL,
    MinGuests int NULL,
    MaxGuests int NULL,
    MinAge int NULL,
    MaxAge int NULL,
    IsFeatured boolean NOT NULL,
    IsFeaturedOnHome boolean NOT NULL,
    IsPrivateTourSupported boolean NOT NULL,
    IsInstantConfirm boolean NOT NULL,
    CountryCode varchar(10) NULL,
    Province varchar(200) NULL,
    City varchar(200) NULL,
    MeetingPointSummary varchar(1000) NULL,
    ShortDescription varchar(2000) NULL,
    DescriptionMarkdown text NULL,
    DescriptionHtml text NULL,
    HighlightsJson text NULL,
    IncludesJson text NULL,
    ExcludesJson text NULL,
    TermsJson text NULL,
    MetadataJson text NULL,
    CoverImageUrl varchar(1000) NULL,
    CoverMediaAssetId uuid NULL,
    CurrencyCode varchar(10) NOT NULL,
    IsActive boolean NOT NULL,
    IsDeleted boolean NOT NULL,
    CreatedAt datetime NOT NULL,
    CreatedByUserId uuid NULL,
    UpdatedAt datetime NULL,
    UpdatedByUserId uuid NULL,
    varbinary(8) varbinary(8) NOT NULL,
    CONSTRAINT PK_Tours PRIMARY KEY (Id)
);

CREATE TABLE fleet.VehicleModels (
    Id uuid NOT NULL,
    TenantId uuid NOT NULL,
    VehicleType int NOT NULL,
    Manufacturer varchar(100) NOT NULL,
    ModelName varchar(120) NOT NULL,
    ModelYear int NULL,
    MetadataJson text NULL,
    IsActive boolean NOT NULL DEFAULT CAST(1 AS boolean),
    IsDeleted boolean NOT NULL DEFAULT CAST(0 AS boolean),
    CreatedAt datetime NOT NULL,
    CreatedByUserId uuid NULL,
    UpdatedAt datetime NULL,
    UpdatedByUserId uuid NULL,
    varbinary(8) blob NOT NULL,
    CONSTRAINT PK_VehicleModels PRIMARY KEY (Id)
);

CREATE TABLE flight.CabinSeatMaps (
    Id uuid NOT NULL DEFAULT (NEWSEQUENTIALID()),
    TenantId uuid NOT NULL,
    AircraftModelId uuid NOT NULL,
    CabinClass int NOT NULL,
    Code varchar(80) NOT NULL,
    Name varchar(200) NOT NULL,
    TotalRows int NOT NULL,
    TotalColumns int NOT NULL,
    LayoutVersion varchar(50) NULL,
    SeatLabelScheme varchar(50) NULL,
    IsActive boolean NOT NULL DEFAULT CAST(1 AS boolean),
    IsDeleted boolean NOT NULL DEFAULT CAST(0 AS boolean),
    CreatedAt datetime NOT NULL DEFAULT (SWITCHOFFSET(SYSDATETIMEOFFSET(), '+07:00')),
    CreatedByUserId uuid NULL,
    UpdatedAt datetime NULL,
    UpdatedByUserId uuid NULL,
    varbinary(8) varbinary(8) NOT NULL,
    CONSTRAINT PK_CabinSeatMaps PRIMARY KEY (Id),
    CONSTRAINT CK_flight_CabinSeatMaps_Cols CHECK (TotalColumns > 0),
    CONSTRAINT CK_flight_CabinSeatMaps_Rows CHECK (TotalRows > 0),
    CONSTRAINT FK_CabinSeatMaps_AircraftModels_AircraftModelId FOREIGN KEY (AircraftModelId) REFERENCES flight.AircraftModels (Id) ON DELETE NO ACTION
);

CREATE TABLE flight.Aircrafts (
    Id uuid NOT NULL DEFAULT (NEWSEQUENTIALID()),
    TenantId uuid NOT NULL,
    AircraftModelId uuid NOT NULL,
    AirlineId uuid NOT NULL,
    Code varchar(50) NOT NULL,
    Registration varchar(30) NULL,
    Name varchar(200) NULL,
    IsActive boolean NOT NULL DEFAULT CAST(1 AS boolean),
    IsDeleted boolean NOT NULL DEFAULT CAST(0 AS boolean),
    CreatedAt datetime NOT NULL DEFAULT (SWITCHOFFSET(SYSDATETIMEOFFSET(), '+07:00')),
    CreatedByUserId uuid NULL,
    UpdatedAt datetime NULL,
    UpdatedByUserId uuid NULL,
    varbinary(8) varbinary(8) NOT NULL,
    CONSTRAINT PK_Aircrafts PRIMARY KEY (Id),
    CONSTRAINT FK_Aircrafts_AircraftModels_AircraftModelId FOREIGN KEY (AircraftModelId) REFERENCES flight.AircraftModels (Id) ON DELETE NO ACTION,
    CONSTRAINT FK_Aircrafts_Airlines_AirlineId FOREIGN KEY (AirlineId) REFERENCES flight.Airlines (Id) ON DELETE NO ACTION
);

CREATE TABLE flight.AncillaryDefinitions (
    Id uuid NOT NULL DEFAULT (NEWSEQUENTIALID()),
    TenantId uuid NOT NULL,
    AirlineId uuid NOT NULL,
    Code varchar(80) NOT NULL,
    Name varchar(200) NOT NULL,
    Type int NOT NULL,
    CurrencyCode char(3) NOT NULL,
    Price decimal(18,2) NOT NULL,
    RulesJson text NULL,
    IsActive boolean NOT NULL DEFAULT CAST(1 AS boolean),
    IsDeleted boolean NOT NULL DEFAULT CAST(0 AS boolean),
    CreatedAt datetime NOT NULL DEFAULT (SWITCHOFFSET(SYSDATETIMEOFFSET(), '+07:00')),
    CreatedByUserId uuid NULL,
    UpdatedAt datetime NULL,
    UpdatedByUserId uuid NULL,
    varbinary(8) varbinary(8) NOT NULL,
    CONSTRAINT PK_AncillaryDefinitions PRIMARY KEY (Id),
    CONSTRAINT FK_AncillaryDefinitions_Airlines_AirlineId FOREIGN KEY (AirlineId) REFERENCES flight.Airlines (Id) ON DELETE NO ACTION
);

CREATE TABLE flight.FareClasses (
    Id uuid NOT NULL DEFAULT (NEWSEQUENTIALID()),
    TenantId uuid NOT NULL,
    AirlineId uuid NOT NULL,
    Code varchar(10) NOT NULL,
    Name varchar(200) NOT NULL,
    CabinClass int NOT NULL,
    IsRefundable boolean NOT NULL DEFAULT CAST(0 AS boolean),
    IsChangeable boolean NOT NULL DEFAULT CAST(0 AS boolean),
    IsActive boolean NOT NULL DEFAULT CAST(1 AS boolean),
    IsDeleted boolean NOT NULL DEFAULT CAST(0 AS boolean),
    CreatedAt datetime NOT NULL DEFAULT (SWITCHOFFSET(SYSDATETIMEOFFSET(), '+07:00')),
    CreatedByUserId uuid NULL,
    UpdatedAt datetime NULL,
    UpdatedByUserId uuid NULL,
    varbinary(8) varbinary(8) NOT NULL,
    CONSTRAINT PK_FareClasses PRIMARY KEY (Id),
    CONSTRAINT FK_FareClasses_Airlines_AirlineId FOREIGN KEY (AirlineId) REFERENCES flight.Airlines (Id) ON DELETE NO ACTION
);

CREATE TABLE AspNetRoleClaims (
    Id int NOT NULL IDENTITY,
    RoleId uuid NOT NULL,
    ClaimType text NULL,
    ClaimValue text NULL,
    CONSTRAINT PK_AspNetRoleClaims PRIMARY KEY (Id),
    CONSTRAINT FK_AspNetRoleClaims_AspNetRoles_RoleId FOREIGN KEY (RoleId) REFERENCES AspNetRoles (Id) ON DELETE CASCADE
);

CREATE TABLE AspNetUserClaims (
    Id int NOT NULL IDENTITY,
    UserId uuid NOT NULL,
    ClaimType text NULL,
    ClaimValue text NULL,
    CONSTRAINT PK_AspNetUserClaims PRIMARY KEY (Id),
    CONSTRAINT FK_AspNetUserClaims_AspNetUsers_UserId FOREIGN KEY (UserId) REFERENCES AspNetUsers (Id) ON DELETE CASCADE
);

CREATE TABLE AspNetUserLogins (
    LoginProvider varchar(450) NOT NULL,
    ProviderKey varchar(450) NOT NULL,
    ProviderDisplayName text NULL,
    UserId uuid NOT NULL,
    CONSTRAINT PK_AspNetUserLogins PRIMARY KEY (LoginProvider, ProviderKey),
    CONSTRAINT FK_AspNetUserLogins_AspNetUsers_UserId FOREIGN KEY (UserId) REFERENCES AspNetUsers (Id) ON DELETE CASCADE
);

CREATE TABLE AspNetUserRoles (
    UserId uuid NOT NULL,
    RoleId uuid NOT NULL,
    CONSTRAINT PK_AspNetUserRoles PRIMARY KEY (UserId, RoleId),
    CONSTRAINT FK_AspNetUserRoles_AspNetRoles_RoleId FOREIGN KEY (RoleId) REFERENCES AspNetRoles (Id) ON DELETE CASCADE,
    CONSTRAINT FK_AspNetUserRoles_AspNetUsers_UserId FOREIGN KEY (UserId) REFERENCES AspNetUsers (Id) ON DELETE CASCADE
);

CREATE TABLE AspNetUserTokens (
    UserId uuid NOT NULL,
    LoginProvider varchar(450) NOT NULL,
    Name varchar(450) NOT NULL,
    Value text NULL,
    CONSTRAINT PK_AspNetUserTokens PRIMARY KEY (UserId, LoginProvider, Name),
    CONSTRAINT FK_AspNetUserTokens_AspNetUsers_UserId FOREIGN KEY (UserId) REFERENCES AspNetUsers (Id) ON DELETE CASCADE
);

CREATE TABLE hotels.CancellationPolicies (
    Id uuid NOT NULL,
    TenantId uuid NOT NULL,
    HotelId uuid NOT NULL,
    Code varchar(80) NOT NULL,
    Name varchar(300) NOT NULL,
    Type int NOT NULL,
    Description varchar(2000) NULL,
    MetadataJson text NULL,
    IsActive boolean NOT NULL,
    IsDeleted boolean NOT NULL,
    CreatedAt datetime NOT NULL,
    CreatedByUserId uuid NULL,
    UpdatedAt datetime NULL,
    UpdatedByUserId uuid NULL,
    varbinary(8) varbinary(8) NOT NULL,
    CONSTRAINT PK_CancellationPolicies PRIMARY KEY (Id),
    CONSTRAINT FK_CancellationPolicies_Hotels_HotelId FOREIGN KEY (HotelId) REFERENCES hotels.Hotels (Id) ON DELETE NO ACTION
);

CREATE TABLE hotels.CheckInOutRules (
    Id uuid NOT NULL,
    TenantId uuid NOT NULL,
    HotelId uuid NOT NULL,
    Code varchar(80) NOT NULL,
    Name varchar(300) NOT NULL,
    CheckInFrom time(0) NOT NULL,
    CheckInTo time(0) NOT NULL,
    CheckOutFrom time(0) NOT NULL,
    CheckOutTo time(0) NOT NULL,
    AllowsEarlyCheckIn boolean NOT NULL,
    AllowsLateCheckOut boolean NOT NULL,
    Notes varchar(2000) NULL,
    IsActive boolean NOT NULL,
    IsDeleted boolean NOT NULL,
    CreatedAt datetime NOT NULL,
    CreatedByUserId uuid NULL,
    UpdatedAt datetime NULL,
    UpdatedByUserId uuid NULL,
    varbinary(8) varbinary(8) NOT NULL,
    CONSTRAINT PK_CheckInOutRules PRIMARY KEY (Id),
    CONSTRAINT FK_CheckInOutRules_Hotels_HotelId FOREIGN KEY (HotelId) REFERENCES hotels.Hotels (Id) ON DELETE NO ACTION
);

CREATE TABLE hotels.ExtraServices (
    Id uuid NOT NULL,
    TenantId uuid NOT NULL,
    HotelId uuid NOT NULL,
    Code varchar(80) NOT NULL,
    Name varchar(300) NOT NULL,
    Description varchar(2000) NULL,
    Type int NOT NULL,
    Unit int NOT NULL,
    Taxable boolean NOT NULL,
    MetadataJson text NULL,
    IsActive boolean NOT NULL,
    IsDeleted boolean NOT NULL,
    CreatedAt datetime NOT NULL,
    CreatedByUserId uuid NULL,
    UpdatedAt datetime NULL,
    UpdatedByUserId uuid NULL,
    varbinary(8) varbinary(8) NOT NULL,
    CONSTRAINT PK_ExtraServices PRIMARY KEY (Id),
    CONSTRAINT FK_ExtraServices_Hotels_HotelId FOREIGN KEY (HotelId) REFERENCES hotels.Hotels (Id) ON DELETE NO ACTION
);

CREATE TABLE hotels.HotelAmenityLinks (
    Id uuid NOT NULL,
    TenantId uuid NOT NULL,
    HotelId uuid NOT NULL,
    AmenityId uuid NOT NULL,
    IsHighlighted boolean NOT NULL,
    Notes varchar(2000) NULL,
    IsDeleted boolean NOT NULL,
    CreatedAt datetime NOT NULL,
    CreatedByUserId uuid NULL,
    UpdatedAt datetime NULL,
    UpdatedByUserId uuid NULL,
    varbinary(8) varbinary(8) NOT NULL,
    CONSTRAINT PK_HotelAmenityLinks PRIMARY KEY (Id),
    CONSTRAINT FK_HotelAmenityLinks_HotelAmenities_AmenityId FOREIGN KEY (AmenityId) REFERENCES hotels.HotelAmenities (Id) ON DELETE NO ACTION,
    CONSTRAINT FK_HotelAmenityLinks_Hotels_HotelId FOREIGN KEY (HotelId) REFERENCES hotels.Hotels (Id) ON DELETE NO ACTION
);

CREATE TABLE hotels.HotelContacts (
    Id uuid NOT NULL,
    TenantId uuid NOT NULL,
    HotelId uuid NOT NULL,
    ContactName varchar(200) NOT NULL,
    RoleTitle varchar(200) NULL,
    Phone varchar(50) NULL,
    Email varchar(200) NULL,
    Notes varchar(2000) NULL,
    IsPrimary boolean NOT NULL,
    IsActive boolean NOT NULL,
    IsDeleted boolean NOT NULL,
    CreatedAt datetime NOT NULL,
    CreatedByUserId uuid NULL,
    UpdatedAt datetime NULL,
    UpdatedByUserId uuid NULL,
    varbinary(8) varbinary(8) NOT NULL,
    CONSTRAINT PK_HotelContacts PRIMARY KEY (Id),
    CONSTRAINT FK_HotelContacts_Hotels_HotelId FOREIGN KEY (HotelId) REFERENCES hotels.Hotels (Id) ON DELETE NO ACTION
);

CREATE TABLE hotels.HotelImages (
    Id uuid NOT NULL,
    TenantId uuid NOT NULL,
    HotelId uuid NOT NULL,
    Kind int NOT NULL,
    SortOrder int NOT NULL,
    MediaAssetId uuid NULL,
    ImageUrl varchar(1000) NULL,
    Title varchar(200) NULL,
    AltText varchar(300) NULL,
    IsActive boolean NOT NULL,
    IsDeleted boolean NOT NULL,
    CreatedAt datetime NOT NULL,
    CreatedByUserId uuid NULL,
    UpdatedAt datetime NULL,
    UpdatedByUserId uuid NULL,
    varbinary(8) varbinary(8) NOT NULL,
    CONSTRAINT PK_HotelImages PRIMARY KEY (Id),
    CONSTRAINT FK_HotelImages_Hotels_HotelId FOREIGN KEY (HotelId) REFERENCES hotels.Hotels (Id) ON DELETE NO ACTION
);

CREATE TABLE hotels.HotelReviews (
    Id uuid NOT NULL,
    TenantId uuid NOT NULL,
    HotelId uuid NOT NULL,
    BookingId uuid NULL,
    CustomerUserId uuid NULL,
    Rating int NOT NULL,
    Title varchar(300) NULL,
    Content text NULL,
    Status int NOT NULL,
    IsVerifiedStay boolean NOT NULL,
    HelpfulCount int NOT NULL,
    MetadataJson text NULL,
    IsDeleted boolean NOT NULL,
    CreatedAt datetime NOT NULL,
    CreatedByUserId uuid NULL,
    UpdatedAt datetime NULL,
    UpdatedByUserId uuid NULL,
    varbinary(8) varbinary(8) NOT NULL,
    CONSTRAINT PK_HotelReviews PRIMARY KEY (Id),
    CONSTRAINT FK_HotelReviews_Hotels_HotelId FOREIGN KEY (HotelId) REFERENCES hotels.Hotels (Id) ON DELETE NO ACTION
);

CREATE TABLE hotels.PropertyPolicies (
    Id uuid NOT NULL,
    TenantId uuid NOT NULL,
    HotelId uuid NOT NULL,
    Code varchar(80) NOT NULL,
    Name varchar(300) NOT NULL,
    PolicyJson text NULL,
    Notes varchar(2000) NULL,
    IsActive boolean NOT NULL,
    IsDeleted boolean NOT NULL,
    CreatedAt datetime NOT NULL,
    CreatedByUserId uuid NULL,
    UpdatedAt datetime NULL,
    UpdatedByUserId uuid NULL,
    varbinary(8) varbinary(8) NOT NULL,
    CONSTRAINT PK_PropertyPolicies PRIMARY KEY (Id),
    CONSTRAINT FK_PropertyPolicies_Hotels_HotelId FOREIGN KEY (HotelId) REFERENCES hotels.Hotels (Id) ON DELETE NO ACTION
);

CREATE TABLE hotels.RoomTypes (
    Id uuid NOT NULL,
    TenantId uuid NOT NULL,
    HotelId uuid NOT NULL,
    Code varchar(50) NOT NULL,
    Name varchar(300) NOT NULL,
    DescriptionMarkdown text NULL,
    DescriptionHtml text NULL,
    SortOrder int NOT NULL,
    AreaSquareMeters int NULL,
    HasBalcony boolean NULL,
    HasWindow boolean NULL,
    SmokingAllowed boolean NULL,
    DefaultAdults int NOT NULL,
    DefaultChildren int NOT NULL,
    MaxAdults int NOT NULL,
    MaxChildren int NOT NULL,
    MaxGuests int NOT NULL,
    TotalUnits int NOT NULL,
    CoverMediaAssetId uuid NULL,
    CoverImageUrl varchar(1000) NULL,
    Status int NOT NULL,
    IsActive boolean NOT NULL,
    MetadataJson text NULL,
    IsDeleted boolean NOT NULL,
    CreatedAt datetime NOT NULL,
    CreatedByUserId uuid NULL,
    UpdatedAt datetime NULL,
    UpdatedByUserId uuid NULL,
    varbinary(8) varbinary(8) NOT NULL,
    CONSTRAINT PK_RoomTypes PRIMARY KEY (Id),
    CONSTRAINT FK_RoomTypes_Hotels_HotelId FOREIGN KEY (HotelId) REFERENCES hotels.Hotels (Id) ON DELETE NO ACTION
);

CREATE TABLE cms.NewsPosts (
    Id uuid NOT NULL,
    TenantId uuid NOT NULL,
    Title varchar(300) NOT NULL,
    Slug varchar(300) NOT NULL,
    Summary varchar(2000) NULL,
    ContentMarkdown text NOT NULL,
    ContentHtml text NOT NULL,
    CoverMediaAssetId uuid NULL,
    CoverImageUrl varchar(1000) NULL,
    SeoTitle varchar(300) NULL,
    SeoDescription varchar(2000) NULL,
    SeoKeywords varchar(2000) NULL,
    CanonicalUrl varchar(1000) NULL,
    Robots varchar(200) NULL,
    OgTitle varchar(300) NULL,
    OgDescription varchar(2000) NULL,
    OgImageUrl varchar(1000) NULL,
    OgType varchar(50) NULL,
    TwitterCard varchar(50) NULL,
    TwitterSite varchar(100) NULL,
    TwitterCreator varchar(100) NULL,
    TwitterTitle varchar(300) NULL,
    TwitterDescription varchar(2000) NULL,
    TwitterImageUrl varchar(1000) NULL,
    SchemaJsonLd text NULL,
    Status int NOT NULL,
    ScheduledAt datetime NULL,
    PublishedAt datetime NULL,
    UnpublishedAt datetime NULL,
    AuthorUserId uuid NULL,
    EditorUserId uuid NULL,
    LastEditedAt datetime NULL,
    ViewCount int NOT NULL,
    WordCount int NOT NULL,
    ReadingTimeMinutes int NOT NULL,
    IsDeleted boolean NOT NULL,
    CreatedAt datetime NOT NULL,
    CreatedByUserId uuid NULL,
    UpdatedAt datetime NULL,
    UpdatedByUserId uuid NULL,
    varbinary(8) blob NOT NULL,
    CONSTRAINT PK_NewsPosts PRIMARY KEY (Id),
    CONSTRAINT FK_NewsPosts_AspNetUsers_AuthorUserId FOREIGN KEY (AuthorUserId) REFERENCES AspNetUsers (Id),
    CONSTRAINT FK_NewsPosts_AspNetUsers_EditorUserId FOREIGN KEY (EditorUserId) REFERENCES AspNetUsers (Id),
    CONSTRAINT FK_NewsPosts_MediaAssets_CoverMediaAssetId FOREIGN KEY (CoverMediaAssetId) REFERENCES cms.MediaAssets (Id) ON DELETE SET NULL
);

CREATE TABLE auth.RolePermissions (
    Id uuid NOT NULL,
    RoleId uuid NOT NULL,
    PermissionId uuid NOT NULL,
    IsDeleted boolean NOT NULL DEFAULT CAST(0 AS boolean),
    CreatedAt datetime NOT NULL,
    CreatedByUserId uuid NULL,
    UpdatedAt datetime NULL,
    UpdatedByUserId uuid NULL,
    varbinary(8) varbinary(8) NOT NULL,
    CONSTRAINT PK_RolePermissions PRIMARY KEY (Id),
    CONSTRAINT FK_RolePermissions_AspNetRoles_RoleId FOREIGN KEY (RoleId) REFERENCES AspNetRoles (Id) ON DELETE NO ACTION,
    CONSTRAINT FK_RolePermissions_Permissions_PermissionId FOREIGN KEY (PermissionId) REFERENCES auth.Permissions (Id) ON DELETE NO ACTION
);

CREATE TABLE auth.UserPermissions (
    Id uuid NOT NULL,
    UserId uuid NOT NULL,
    PermissionId uuid NOT NULL,
    TenantId uuid NULL,
    Effect int NOT NULL,
    Reason varchar(500) NULL,
    IsDeleted boolean NOT NULL DEFAULT CAST(0 AS boolean),
    CreatedAt datetime NOT NULL,
    CreatedByUserId uuid NULL,
    UpdatedAt datetime NULL,
    UpdatedByUserId uuid NULL,
    varbinary(8) varbinary(8) NOT NULL,
    CONSTRAINT PK_UserPermissions PRIMARY KEY (Id),
    CONSTRAINT FK_UserPermissions_AspNetUsers_UserId FOREIGN KEY (UserId) REFERENCES AspNetUsers (Id) ON DELETE NO ACTION,
    CONSTRAINT FK_UserPermissions_Permissions_PermissionId FOREIGN KEY (PermissionId) REFERENCES auth.Permissions (Id) ON DELETE NO ACTION
);

CREATE TABLE geo.Districts (
    Id uuid NOT NULL,
    Code int NOT NULL,
    Name varchar(200) NOT NULL,
    NameEn varchar(200) NULL,
    Slug varchar(250) NULL,
    Type varchar(50) NULL,
    ProvinceId uuid NOT NULL,
    IsActive boolean NOT NULL DEFAULT CAST(1 AS boolean),
    CreatedAt datetime NOT NULL,
    UpdatedAt datetime NULL,
    CONSTRAINT PK_Districts PRIMARY KEY (Id),
    CONSTRAINT FK_Districts_Provinces_ProvinceId FOREIGN KEY (ProvinceId) REFERENCES geo.Provinces (Id) ON DELETE NO ACTION
);

CREATE TABLE fleet.Seats (
    Id uuid NOT NULL,
    TenantId uuid NOT NULL,
    SeatMapId uuid NOT NULL,
    SeatNumber varchar(20) NOT NULL,
    RowIndex int NOT NULL,
    ColumnIndex int NOT NULL,
    DeckIndex int NOT NULL,
    SeatType int NOT NULL,
    SeatClass int NOT NULL,
    IsAisle boolean NOT NULL,
    IsWindow boolean NOT NULL,
    PriceModifier decimal(18,2) NULL,
    IsActive boolean NOT NULL DEFAULT CAST(1 AS boolean),
    IsDeleted boolean NOT NULL DEFAULT CAST(0 AS boolean),
    CreatedAt datetime NOT NULL,
    CreatedByUserId uuid NULL,
    UpdatedAt datetime NULL,
    UpdatedByUserId uuid NULL,
    varbinary(8) blob NOT NULL,
    CONSTRAINT PK_Seats PRIMARY KEY (Id),
    CONSTRAINT FK_Seats_SeatMaps_SeatMapId FOREIGN KEY (SeatMapId) REFERENCES fleet.SeatMaps (Id) ON DELETE NO ACTION
);

CREATE TABLE tenants.TenantRoles (
    Id uuid NOT NULL,
    TenantId uuid NOT NULL,
    Code varchar(80) NOT NULL,
    Name varchar(200) NOT NULL,
    Description varchar(1000) NULL,
    IsActive boolean NOT NULL DEFAULT CAST(1 AS boolean),
    IsDeleted boolean NOT NULL DEFAULT CAST(0 AS boolean),
    CreatedAt datetime NOT NULL,
    CreatedByUserId uuid NULL,
    UpdatedAt datetime NULL,
    UpdatedByUserId uuid NULL,
    varbinary(8) varbinary(8) NOT NULL,
    CONSTRAINT PK_TenantRoles PRIMARY KEY (Id),
    CONSTRAINT FK_TenantRoles_Tenants_TenantId FOREIGN KEY (TenantId) REFERENCES tenants.Tenants (Id) ON DELETE NO ACTION
);

CREATE TABLE tenants.TenantUsers (
    Id uuid NOT NULL,
    TenantId uuid NOT NULL,
    UserId uuid NOT NULL,
    RoleName varchar(50) NOT NULL,
    IsOwner boolean NOT NULL,
    IsDeleted boolean NOT NULL DEFAULT CAST(0 AS boolean),
    CreatedAt datetime NOT NULL,
    CreatedByUserId uuid NULL,
    UpdatedAt datetime NULL,
    UpdatedByUserId uuid NULL,
    varbinary(8) blob NOT NULL,
    CONSTRAINT PK_TenantUsers PRIMARY KEY (Id),
    CONSTRAINT FK_TenantUsers_AspNetUsers_UserId FOREIGN KEY (UserId) REFERENCES AspNetUsers (Id) ON DELETE NO ACTION,
    CONSTRAINT FK_TenantUsers_Tenants_TenantId FOREIGN KEY (TenantId) REFERENCES tenants.Tenants (Id) ON DELETE NO ACTION
);

CREATE TABLE tours.TourAddons (
    Id uuid NOT NULL,
    TenantId uuid NOT NULL,
    TourId uuid NOT NULL,
    Code varchar(50) NOT NULL,
    Name varchar(300) NOT NULL,
    Type int NOT NULL,
    ShortDescription varchar(2000) NULL,
    DescriptionMarkdown text NULL,
    DescriptionHtml text NULL,
    CurrencyCode varchar(10) NOT NULL,
    BasePrice decimal(18,2) NOT NULL,
    OriginalPrice decimal(18,2) NULL,
    IsPerPerson boolean NOT NULL,
    IsRequired boolean NOT NULL,
    AllowQuantitySelection boolean NOT NULL,
    MinQuantity int NULL,
    MaxQuantity int NULL,
    IsDefaultSelected boolean NOT NULL,
    Notes varchar(2000) NULL,
    MetadataJson text NULL,
    SortOrder int NOT NULL,
    IsActive boolean NOT NULL,
    IsDeleted boolean NOT NULL,
    CreatedAt datetime NOT NULL,
    CreatedByUserId uuid NULL,
    UpdatedAt datetime NULL,
    UpdatedByUserId uuid NULL,
    varbinary(8) varbinary(8) NOT NULL,
    CONSTRAINT PK_TourAddons PRIMARY KEY (Id),
    CONSTRAINT FK_TourAddons_Tours_TourId FOREIGN KEY (TourId) REFERENCES tours.Tours (Id) ON DELETE NO ACTION
);

CREATE TABLE tours.TourContacts (
    Id uuid NOT NULL,
    TenantId uuid NOT NULL,
    TourId uuid NOT NULL,
    Name varchar(200) NOT NULL,
    Title varchar(200) NULL,
    Department varchar(200) NULL,
    Phone varchar(50) NULL,
    Email varchar(200) NULL,
    ContactType int NOT NULL,
    IsPrimary boolean NOT NULL,
    SortOrder int NOT NULL,
    Notes varchar(2000) NULL,
    MetadataJson text NULL,
    IsActive boolean NOT NULL,
    IsDeleted boolean NOT NULL,
    CreatedAt datetime NOT NULL,
    CreatedByUserId uuid NULL,
    UpdatedAt datetime NULL,
    UpdatedByUserId uuid NULL,
    varbinary(8) varbinary(8) NOT NULL,
    CONSTRAINT PK_TourContacts PRIMARY KEY (Id),
    CONSTRAINT FK_TourContacts_Tours_TourId FOREIGN KEY (TourId) REFERENCES tours.Tours (Id) ON DELETE NO ACTION
);

CREATE TABLE tours.TourDropoffPoints (
    Id uuid NOT NULL,
    TenantId uuid NOT NULL,
    TourId uuid NOT NULL,
    Code varchar(50) NOT NULL,
    Name varchar(300) NOT NULL,
    AddressLine varchar(500) NULL,
    Ward varchar(200) NULL,
    District varchar(200) NULL,
    Province varchar(200) NULL,
    CountryCode varchar(10) NULL,
    Latitude decimal(18,6) NULL,
    Longitude decimal(18,6) NULL,
    DropoffTime time NULL,
    Notes varchar(2000) NULL,
    MetadataJson text NULL,
    IsDefault boolean NOT NULL,
    SortOrder int NOT NULL,
    IsActive boolean NOT NULL,
    IsDeleted boolean NOT NULL,
    CreatedAt datetime NOT NULL,
    CreatedByUserId uuid NULL,
    UpdatedAt datetime NULL,
    UpdatedByUserId uuid NULL,
    varbinary(8) varbinary(8) NOT NULL,
    CONSTRAINT PK_TourDropoffPoints PRIMARY KEY (Id),
    CONSTRAINT FK_TourDropoffPoints_Tours_TourId FOREIGN KEY (TourId) REFERENCES tours.Tours (Id) ON DELETE NO ACTION
);

CREATE TABLE tours.TourFaqs (
    Id uuid NOT NULL,
    TenantId uuid NOT NULL,
    TourId uuid NOT NULL,
    Question varchar(1000) NOT NULL,
    AnswerMarkdown text NOT NULL,
    AnswerHtml text NULL,
    Type int NOT NULL,
    IsHighlighted boolean NOT NULL,
    SortOrder int NOT NULL,
    Notes varchar(2000) NULL,
    MetadataJson text NULL,
    IsActive boolean NOT NULL,
    IsDeleted boolean NOT NULL,
    CreatedAt datetime NOT NULL,
    CreatedByUserId uuid NULL,
    UpdatedAt datetime NULL,
    UpdatedByUserId uuid NULL,
    varbinary(8) varbinary(8) NOT NULL,
    CONSTRAINT PK_TourFaqs PRIMARY KEY (Id),
    CONSTRAINT FK_TourFaqs_Tours_TourId FOREIGN KEY (TourId) REFERENCES tours.Tours (Id) ON DELETE NO ACTION
);

CREATE TABLE tours.TourImages (
    Id uuid NOT NULL,
    TenantId uuid NOT NULL,
    TourId uuid NOT NULL,
    MediaAssetId uuid NULL,
    ImageUrl varchar(1000) NULL,
    Caption varchar(500) NULL,
    AltText varchar(500) NULL,
    Title varchar(500) NULL,
    IsPrimary boolean NOT NULL,
    IsCover boolean NOT NULL,
    IsFeatured boolean NOT NULL,
    SortOrder int NOT NULL,
    MetadataJson text NULL,
    IsActive boolean NOT NULL,
    IsDeleted boolean NOT NULL,
    CreatedAt datetime NOT NULL,
    CreatedByUserId uuid NULL,
    UpdatedAt datetime NULL,
    UpdatedByUserId uuid NULL,
    varbinary(8) varbinary(8) NOT NULL,
    CONSTRAINT PK_TourImages PRIMARY KEY (Id),
    CONSTRAINT FK_TourImages_Tours_TourId FOREIGN KEY (TourId) REFERENCES tours.Tours (Id) ON DELETE NO ACTION
);

CREATE TABLE tours.TourItineraryDays (
    Id uuid NOT NULL,
    TenantId uuid NOT NULL,
    TourId uuid NOT NULL,
    DayNumber int NOT NULL,
    Title varchar(300) NOT NULL,
    ShortDescription varchar(2000) NULL,
    DescriptionMarkdown text NULL,
    DescriptionHtml text NULL,
    StartLocation varchar(300) NULL,
    EndLocation varchar(300) NULL,
    AccommodationName varchar(300) NULL,
    IncludesBreakfast boolean NOT NULL,
    IncludesLunch boolean NOT NULL,
    IncludesDinner boolean NOT NULL,
    TransportationSummary varchar(1000) NULL,
    Notes varchar(2000) NULL,
    MetadataJson text NULL,
    SortOrder int NOT NULL,
    IsActive boolean NOT NULL,
    IsDeleted boolean NOT NULL,
    CreatedAt datetime NOT NULL,
    CreatedByUserId uuid NULL,
    UpdatedAt datetime NULL,
    UpdatedByUserId uuid NULL,
    varbinary(8) varbinary(8) NOT NULL,
    CONSTRAINT PK_TourItineraryDays PRIMARY KEY (Id),
    CONSTRAINT FK_TourItineraryDays_Tours_TourId FOREIGN KEY (TourId) REFERENCES tours.Tours (Id) ON DELETE NO ACTION
);

CREATE TABLE tours.TourPickupPoints (
    Id uuid NOT NULL,
    TenantId uuid NOT NULL,
    TourId uuid NOT NULL,
    Code varchar(50) NOT NULL,
    Name varchar(300) NOT NULL,
    AddressLine varchar(500) NULL,
    Ward varchar(200) NULL,
    District varchar(200) NULL,
    Province varchar(200) NULL,
    CountryCode varchar(10) NULL,
    Latitude decimal(18,6) NULL,
    Longitude decimal(18,6) NULL,
    PickupTime time NULL,
    Notes varchar(2000) NULL,
    MetadataJson text NULL,
    IsDefault boolean NOT NULL,
    SortOrder int NOT NULL,
    IsActive boolean NOT NULL,
    IsDeleted boolean NOT NULL,
    CreatedAt datetime NOT NULL,
    CreatedByUserId uuid NULL,
    UpdatedAt datetime NULL,
    UpdatedByUserId uuid NULL,
    varbinary(8) varbinary(8) NOT NULL,
    CONSTRAINT PK_TourPickupPoints PRIMARY KEY (Id),
    CONSTRAINT FK_TourPickupPoints_Tours_TourId FOREIGN KEY (TourId) REFERENCES tours.Tours (Id) ON DELETE NO ACTION
);

CREATE TABLE tours.TourPolicies (
    Id uuid NOT NULL,
    TenantId uuid NOT NULL,
    TourId uuid NOT NULL,
    Code varchar(50) NOT NULL,
    Name varchar(300) NOT NULL,
    Type int NOT NULL,
    ShortDescription varchar(2000) NULL,
    DescriptionMarkdown text NULL,
    DescriptionHtml text NULL,
    PolicyJson text NULL,
    IsHighlighted boolean NOT NULL,
    SortOrder int NOT NULL,
    Notes varchar(2000) NULL,
    MetadataJson text NULL,
    IsActive boolean NOT NULL,
    IsDeleted boolean NOT NULL,
    CreatedAt datetime NOT NULL,
    CreatedByUserId uuid NULL,
    UpdatedAt datetime NULL,
    UpdatedByUserId uuid NULL,
    varbinary(8) varbinary(8) NOT NULL,
    CONSTRAINT PK_TourPolicies PRIMARY KEY (Id),
    CONSTRAINT FK_TourPolicies_Tours_TourId FOREIGN KEY (TourId) REFERENCES tours.Tours (Id) ON DELETE NO ACTION
);

CREATE TABLE tours.TourReviews (
    Id uuid NOT NULL,
    TenantId uuid NOT NULL,
    TourId uuid NOT NULL,
    Rating decimal(4,2) NOT NULL,
    Title varchar(300) NULL,
    Content varchar(4000) NULL,
    ReviewerName varchar(200) NULL,
    Status int NOT NULL,
    IsApproved boolean NOT NULL,
    IsPublic boolean NOT NULL,
    ModerationNote varchar(2000) NULL,
    ReplyContent varchar(4000) NULL,
    ReplyAt datetime NULL,
    ReplyByUserId uuid NULL,
    PublishedAt datetime NULL,
    ApprovedAt datetime NULL,
    ApprovedByUserId uuid NULL,
    MetadataJson text NULL,
    IsDeleted boolean NOT NULL,
    CreatedAt datetime NOT NULL,
    CreatedByUserId uuid NULL,
    UpdatedAt datetime NULL,
    UpdatedByUserId uuid NULL,
    varbinary(8) varbinary(8) NOT NULL,
    CONSTRAINT PK_TourReviews PRIMARY KEY (Id),
    CONSTRAINT FK_TourReviews_Tours_TourId FOREIGN KEY (TourId) REFERENCES tours.Tours (Id) ON DELETE NO ACTION
);

CREATE TABLE tours.TourSchedules (
    Id uuid NOT NULL,
    TenantId uuid NOT NULL,
    TourId uuid NOT NULL,
    Code varchar(50) NOT NULL,
    Name varchar(300) NULL,
    DepartureDate date NOT NULL,
    ReturnDate date NOT NULL,
    DepartureTime time NULL,
    ReturnTime time NULL,
    BookingOpenAt datetime NULL,
    BookingCutoffAt datetime NULL,
    MeetingPointSummary varchar(1000) NULL,
    PickupSummary varchar(1000) NULL,
    DropoffSummary varchar(1000) NULL,
    Notes varchar(4000) NULL,
    InternalNotes varchar(4000) NULL,
    CancellationNotes varchar(4000) NULL,
    MetadataJson text NULL,
    Status int NOT NULL,
    IsGuaranteedDeparture boolean NOT NULL,
    IsInstantConfirm boolean NOT NULL,
    IsFeatured boolean NOT NULL,
    MinGuestsToOperate int NULL,
    MaxGuests int NULL,
    IsActive boolean NOT NULL,
    IsDeleted boolean NOT NULL,
    CreatedAt datetime NOT NULL,
    CreatedByUserId uuid NULL,
    UpdatedAt datetime NULL,
    UpdatedByUserId uuid NULL,
    varbinary(8) varbinary(8) NOT NULL,
    CONSTRAINT PK_TourSchedules PRIMARY KEY (Id),
    CONSTRAINT FK_TourSchedules_Tours_TourId FOREIGN KEY (TourId) REFERENCES tours.Tours (Id) ON DELETE NO ACTION
);

CREATE TABLE flight.CabinSeats (
    Id uuid NOT NULL DEFAULT (NEWSEQUENTIALID()),
    TenantId uuid NOT NULL,
    CabinSeatMapId uuid NOT NULL,
    SeatNumber varchar(10) NOT NULL,
    RowIndex int NOT NULL,
    ColumnIndex int NOT NULL,
    IsAisle boolean NOT NULL,
    IsWindow boolean NOT NULL,
    SeatClass varchar(50) NULL,
    PriceModifier decimal(18,2) NULL,
    IsActive boolean NOT NULL DEFAULT CAST(1 AS boolean),
    IsDeleted boolean NOT NULL DEFAULT CAST(0 AS boolean),
    CreatedAt datetime NOT NULL DEFAULT (SWITCHOFFSET(SYSDATETIMEOFFSET(), '+07:00')),
    CreatedByUserId uuid NULL,
    UpdatedAt datetime NULL,
    UpdatedByUserId uuid NULL,
    varbinary(8) varbinary(8) NOT NULL,
    CONSTRAINT PK_CabinSeats PRIMARY KEY (Id),
    CONSTRAINT FK_CabinSeats_CabinSeatMaps_CabinSeatMapId FOREIGN KEY (CabinSeatMapId) REFERENCES flight.CabinSeatMaps (Id) ON DELETE NO ACTION
);

CREATE TABLE flight.FareRules (
    Id uuid NOT NULL DEFAULT (NEWSEQUENTIALID()),
    TenantId uuid NOT NULL,
    FareClassId uuid NOT NULL,
    RulesJson text NOT NULL DEFAULT N'{}',
    IsActive boolean NOT NULL DEFAULT CAST(1 AS boolean),
    IsDeleted boolean NOT NULL DEFAULT CAST(0 AS boolean),
    CreatedAt datetime NOT NULL DEFAULT (SWITCHOFFSET(SYSDATETIMEOFFSET(), '+07:00')),
    CreatedByUserId uuid NULL,
    UpdatedAt datetime NULL,
    UpdatedByUserId uuid NULL,
    varbinary(8) varbinary(8) NOT NULL,
    CONSTRAINT PK_FareRules PRIMARY KEY (Id),
    CONSTRAINT FK_FareRules_FareClasses_FareClassId FOREIGN KEY (FareClassId) REFERENCES flight.FareClasses (Id) ON DELETE NO ACTION
);

CREATE TABLE hotels.CancellationPolicyRules (
    Id uuid NOT NULL,
    TenantId uuid NOT NULL,
    CancellationPolicyId uuid NOT NULL,
    CancelBeforeHours int NULL,
    CancelBeforeDays int NULL,
    ChargeType int NOT NULL,
    ChargeValue decimal(18,2) NOT NULL,
    CurrencyCode varchar(10) NOT NULL,
    Notes varchar(2000) NULL,
    Priority int NOT NULL,
    IsActive boolean NOT NULL,
    IsDeleted boolean NOT NULL,
    CreatedAt datetime NOT NULL,
    CreatedByUserId uuid NULL,
    UpdatedAt datetime NULL,
    UpdatedByUserId uuid NULL,
    varbinary(8) varbinary(8) NOT NULL,
    CONSTRAINT PK_CancellationPolicyRules PRIMARY KEY (Id),
    CONSTRAINT FK_CancellationPolicyRules_CancellationPolicies_CancellationPolicyId FOREIGN KEY (CancellationPolicyId) REFERENCES hotels.CancellationPolicies (Id) ON DELETE NO ACTION
);

CREATE TABLE hotels.ExtraServicePrices (
    Id uuid NOT NULL,
    TenantId uuid NOT NULL,
    ExtraServiceId uuid NOT NULL,
    StartDate date NOT NULL,
    EndDate date NOT NULL,
    Price decimal(18,2) NOT NULL,
    CurrencyCode varchar(10) NOT NULL,
    IsActive boolean NOT NULL,
    IsDeleted boolean NOT NULL,
    CreatedAt datetime NOT NULL,
    CreatedByUserId uuid NULL,
    UpdatedAt datetime NULL,
    UpdatedByUserId uuid NULL,
    varbinary(8) varbinary(8) NOT NULL,
    CONSTRAINT PK_ExtraServicePrices PRIMARY KEY (Id),
    CONSTRAINT FK_ExtraServicePrices_ExtraServices_ExtraServiceId FOREIGN KEY (ExtraServiceId) REFERENCES hotels.ExtraServices (Id) ON DELETE NO ACTION
);

CREATE TABLE hotels.RatePlans (
    Id uuid NOT NULL,
    TenantId uuid NOT NULL,
    HotelId uuid NOT NULL,
    Code varchar(80) NOT NULL,
    Name varchar(300) NOT NULL,
    Description varchar(2000) NULL,
    Type int NOT NULL,
    Status int NOT NULL,
    CancellationPolicyId uuid NULL,
    CheckInOutRuleId uuid NULL,
    PropertyPolicyId uuid NULL,
    Refundable boolean NOT NULL,
    BreakfastIncluded boolean NOT NULL,
    MinNights int NULL,
    MaxNights int NULL,
    MinAdvanceDays int NULL,
    MaxAdvanceDays int NULL,
    RequiresGuarantee boolean NOT NULL,
    MetadataJson text NULL,
    IsActive boolean NOT NULL,
    IsDeleted boolean NOT NULL,
    CreatedAt datetime NOT NULL,
    CreatedByUserId uuid NULL,
    UpdatedAt datetime NULL,
    UpdatedByUserId uuid NULL,
    varbinary(8) varbinary(8) NOT NULL,
    CONSTRAINT PK_RatePlans PRIMARY KEY (Id),
    CONSTRAINT FK_RatePlans_CancellationPolicies_CancellationPolicyId FOREIGN KEY (CancellationPolicyId) REFERENCES hotels.CancellationPolicies (Id) ON DELETE SET NULL,
    CONSTRAINT FK_RatePlans_CheckInOutRules_CheckInOutRuleId FOREIGN KEY (CheckInOutRuleId) REFERENCES hotels.CheckInOutRules (Id) ON DELETE SET NULL,
    CONSTRAINT FK_RatePlans_Hotels_HotelId FOREIGN KEY (HotelId) REFERENCES hotels.Hotels (Id) ON DELETE NO ACTION,
    CONSTRAINT FK_RatePlans_PropertyPolicies_PropertyPolicyId FOREIGN KEY (PropertyPolicyId) REFERENCES hotels.PropertyPolicies (Id) ON DELETE SET NULL
);

CREATE TABLE hotels.InventoryHolds (
    Id uuid NOT NULL,
    TenantId uuid NOT NULL,
    RoomTypeId uuid NOT NULL,
    BookingId uuid NULL,
    BookingItemId uuid NULL,
    CheckInDate date NOT NULL,
    CheckOutDate date NOT NULL,
    Units int NOT NULL,
    Status int NOT NULL,
    HoldExpiresAt datetime NOT NULL,
    CorrelationId varchar(100) NULL,
    Notes varchar(2000) NULL,
    IsDeleted boolean NOT NULL,
    CreatedAt datetime NOT NULL,
    CreatedByUserId uuid NULL,
    UpdatedAt datetime NULL,
    UpdatedByUserId uuid NULL,
    varbinary(8) varbinary(8) NOT NULL,
    CONSTRAINT PK_InventoryHolds PRIMARY KEY (Id),
    CONSTRAINT FK_InventoryHolds_RoomTypes_RoomTypeId FOREIGN KEY (RoomTypeId) REFERENCES hotels.RoomTypes (Id) ON DELETE NO ACTION
);

CREATE TABLE hotels.RoomAmenityLinks (
    Id uuid NOT NULL,
    TenantId uuid NOT NULL,
    RoomTypeId uuid NOT NULL,
    AmenityId uuid NOT NULL,
    IsHighlighted boolean NOT NULL,
    Notes varchar(2000) NULL,
    IsDeleted boolean NOT NULL,
    CreatedAt datetime NOT NULL,
    CreatedByUserId uuid NULL,
    UpdatedAt datetime NULL,
    UpdatedByUserId uuid NULL,
    varbinary(8) varbinary(8) NOT NULL,
    CONSTRAINT PK_RoomAmenityLinks PRIMARY KEY (Id),
    CONSTRAINT FK_RoomAmenityLinks_RoomAmenities_AmenityId FOREIGN KEY (AmenityId) REFERENCES hotels.RoomAmenities (Id) ON DELETE NO ACTION,
    CONSTRAINT FK_RoomAmenityLinks_RoomTypes_RoomTypeId FOREIGN KEY (RoomTypeId) REFERENCES hotels.RoomTypes (Id) ON DELETE NO ACTION
);

CREATE TABLE hotels.RoomTypeBeds (
    Id uuid NOT NULL,
    TenantId uuid NOT NULL,
    RoomTypeId uuid NOT NULL,
    BedTypeId uuid NOT NULL,
    Quantity int NOT NULL,
    IsDeleted boolean NOT NULL,
    CreatedAt datetime NOT NULL,
    CreatedByUserId uuid NULL,
    UpdatedAt datetime NULL,
    UpdatedByUserId uuid NULL,
    varbinary(8) varbinary(8) NOT NULL,
    CONSTRAINT PK_RoomTypeBeds PRIMARY KEY (Id),
    CONSTRAINT FK_RoomTypeBeds_BedTypes_BedTypeId FOREIGN KEY (BedTypeId) REFERENCES hotels.BedTypes (Id) ON DELETE NO ACTION,
    CONSTRAINT FK_RoomTypeBeds_RoomTypes_RoomTypeId FOREIGN KEY (RoomTypeId) REFERENCES hotels.RoomTypes (Id) ON DELETE NO ACTION
);

CREATE TABLE hotels.RoomTypeImages (
    Id uuid NOT NULL,
    TenantId uuid NOT NULL,
    RoomTypeId uuid NOT NULL,
    Kind int NOT NULL,
    SortOrder int NOT NULL,
    MediaAssetId uuid NULL,
    ImageUrl varchar(1000) NULL,
    Title varchar(200) NULL,
    AltText varchar(300) NULL,
    IsActive boolean NOT NULL,
    IsDeleted boolean NOT NULL,
    CreatedAt datetime NOT NULL,
    CreatedByUserId uuid NULL,
    UpdatedAt datetime NULL,
    UpdatedByUserId uuid NULL,
    varbinary(8) varbinary(8) NOT NULL,
    CONSTRAINT PK_RoomTypeImages PRIMARY KEY (Id),
    CONSTRAINT FK_RoomTypeImages_RoomTypes_RoomTypeId FOREIGN KEY (RoomTypeId) REFERENCES hotels.RoomTypes (Id) ON DELETE NO ACTION
);

CREATE TABLE hotels.RoomTypeInventories (
    Id uuid NOT NULL,
    TenantId uuid NOT NULL,
    RoomTypeId uuid NOT NULL,
    Date date NOT NULL,
    TotalUnits int NOT NULL,
    SoldUnits int NOT NULL,
    HeldUnits int NOT NULL,
    Status int NOT NULL,
    MinNights int NULL,
    MaxNights int NULL,
    Notes varchar(2000) NULL,
    IsDeleted boolean NOT NULL,
    CreatedAt datetime NOT NULL,
    CreatedByUserId uuid NULL,
    UpdatedAt datetime NULL,
    UpdatedByUserId uuid NULL,
    varbinary(8) varbinary(8) NOT NULL,
    CONSTRAINT PK_RoomTypeInventories PRIMARY KEY (Id),
    CONSTRAINT FK_RoomTypeInventories_RoomTypes_RoomTypeId FOREIGN KEY (RoomTypeId) REFERENCES hotels.RoomTypes (Id) ON DELETE NO ACTION
);

CREATE TABLE hotels.RoomTypeMealPlans (
    Id uuid NOT NULL,
    TenantId uuid NOT NULL,
    RoomTypeId uuid NOT NULL,
    MealPlanId uuid NOT NULL,
    IsDefault boolean NOT NULL,
    IsActive boolean NOT NULL,
    IsDeleted boolean NOT NULL,
    CreatedAt datetime NOT NULL,
    CreatedByUserId uuid NULL,
    UpdatedAt datetime NULL,
    UpdatedByUserId uuid NULL,
    varbinary(8) varbinary(8) NOT NULL,
    CONSTRAINT PK_RoomTypeMealPlans PRIMARY KEY (Id),
    CONSTRAINT FK_RoomTypeMealPlans_MealPlans_MealPlanId FOREIGN KEY (MealPlanId) REFERENCES hotels.MealPlans (Id) ON DELETE NO ACTION,
    CONSTRAINT FK_RoomTypeMealPlans_RoomTypes_RoomTypeId FOREIGN KEY (RoomTypeId) REFERENCES hotels.RoomTypes (Id) ON DELETE NO ACTION
);

CREATE TABLE hotels.RoomTypeOccupancyRules (
    Id uuid NOT NULL,
    TenantId uuid NOT NULL,
    RoomTypeId uuid NOT NULL,
    MinAdults int NOT NULL,
    MaxAdults int NOT NULL,
    MinChildren int NOT NULL,
    MaxChildren int NOT NULL,
    MinGuests int NOT NULL,
    MaxGuests int NOT NULL,
    AllowsInfants boolean NOT NULL,
    MaxInfants int NULL,
    Notes varchar(2000) NULL,
    IsActive boolean NOT NULL,
    IsDeleted boolean NOT NULL,
    CreatedAt datetime NOT NULL,
    CreatedByUserId uuid NULL,
    UpdatedAt datetime NULL,
    UpdatedByUserId uuid NULL,
    varbinary(8) varbinary(8) NOT NULL,
    CONSTRAINT PK_RoomTypeOccupancyRules PRIMARY KEY (Id),
    CONSTRAINT FK_RoomTypeOccupancyRules_RoomTypes_RoomTypeId FOREIGN KEY (RoomTypeId) REFERENCES hotels.RoomTypes (Id) ON DELETE NO ACTION
);

CREATE TABLE hotels.RoomTypePolicies (
    Id uuid NOT NULL,
    TenantId uuid NOT NULL,
    RoomTypeId uuid NOT NULL,
    PolicyJson text NULL,
    IsActive boolean NOT NULL,
    IsDeleted boolean NOT NULL,
    CreatedAt datetime NOT NULL,
    CreatedByUserId uuid NULL,
    UpdatedAt datetime NULL,
    UpdatedByUserId uuid NULL,
    varbinary(8) varbinary(8) NOT NULL,
    CONSTRAINT PK_RoomTypePolicies PRIMARY KEY (Id),
    CONSTRAINT FK_RoomTypePolicies_RoomTypes_RoomTypeId FOREIGN KEY (RoomTypeId) REFERENCES hotels.RoomTypes (Id) ON DELETE NO ACTION
);

CREATE TABLE cms.NewsPostCategories (
    Id uuid NOT NULL,
    TenantId uuid NOT NULL,
    PostId uuid NOT NULL,
    CategoryId uuid NOT NULL,
    IsDeleted boolean NOT NULL,
    CreatedAt datetime NOT NULL,
    CreatedByUserId uuid NULL,
    UpdatedAt datetime NULL,
    UpdatedByUserId uuid NULL,
    varbinary(8) blob NOT NULL,
    CONSTRAINT PK_NewsPostCategories PRIMARY KEY (Id),
    CONSTRAINT FK_NewsPostCategories_NewsCategories_CategoryId FOREIGN KEY (CategoryId) REFERENCES cms.NewsCategories (Id) ON DELETE NO ACTION,
    CONSTRAINT FK_NewsPostCategories_NewsPosts_PostId FOREIGN KEY (PostId) REFERENCES cms.NewsPosts (Id) ON DELETE NO ACTION
);

CREATE TABLE cms.NewsPostRevisions (
    Id uuid NOT NULL,
    TenantId uuid NOT NULL,
    PostId uuid NOT NULL,
    VersionNumber int NOT NULL,
    Title varchar(300) NOT NULL,
    Summary varchar(2000) NULL,
    ContentMarkdown text NOT NULL,
    ContentHtml text NOT NULL,
    SeoTitle varchar(300) NULL,
    SeoDescription varchar(2000) NULL,
    CanonicalUrl varchar(1000) NULL,
    Robots varchar(200) NULL,
    OgTitle varchar(300) NULL,
    OgDescription varchar(2000) NULL,
    OgImageUrl varchar(1000) NULL,
    TwitterCard varchar(50) NULL,
    TwitterTitle varchar(300) NULL,
    TwitterDescription varchar(2000) NULL,
    TwitterImageUrl varchar(1000) NULL,
    SchemaJsonLd text NULL,
    ChangeNote varchar(1000) NULL,
    EditorUserId uuid NULL,
    EditedAt datetime NOT NULL,
    IsDeleted boolean NOT NULL,
    CreatedAt datetime NOT NULL,
    CreatedByUserId uuid NULL,
    UpdatedAt datetime NULL,
    UpdatedByUserId uuid NULL,
    varbinary(8) blob NOT NULL,
    CONSTRAINT PK_NewsPostRevisions PRIMARY KEY (Id),
    CONSTRAINT FK_NewsPostRevisions_AspNetUsers_EditorUserId FOREIGN KEY (EditorUserId) REFERENCES AspNetUsers (Id),
    CONSTRAINT FK_NewsPostRevisions_NewsPosts_PostId FOREIGN KEY (PostId) REFERENCES cms.NewsPosts (Id) ON DELETE NO ACTION
);

CREATE TABLE cms.NewsPostTags (
    Id uuid NOT NULL,
    TenantId uuid NOT NULL,
    PostId uuid NOT NULL,
    TagId uuid NOT NULL,
    IsDeleted boolean NOT NULL,
    CreatedAt datetime NOT NULL,
    CreatedByUserId uuid NULL,
    UpdatedAt datetime NULL,
    UpdatedByUserId uuid NULL,
    varbinary(8) blob NOT NULL,
    CONSTRAINT PK_NewsPostTags PRIMARY KEY (Id),
    CONSTRAINT FK_NewsPostTags_NewsPosts_PostId FOREIGN KEY (PostId) REFERENCES cms.NewsPosts (Id) ON DELETE NO ACTION,
    CONSTRAINT FK_NewsPostTags_NewsTags_TagId FOREIGN KEY (TagId) REFERENCES cms.NewsTags (Id) ON DELETE NO ACTION
);

CREATE TABLE geo.Wards (
    Id uuid NOT NULL,
    Code int NOT NULL,
    Name varchar(200) NOT NULL,
    NameEn varchar(200) NULL,
    Slug varchar(250) NULL,
    Type varchar(50) NULL,
    DistrictId uuid NOT NULL,
    IsActive boolean NOT NULL DEFAULT CAST(1 AS boolean),
    CreatedAt datetime NOT NULL,
    UpdatedAt datetime NULL,
    CONSTRAINT PK_Wards PRIMARY KEY (Id),
    CONSTRAINT FK_Wards_Districts_DistrictId FOREIGN KEY (DistrictId) REFERENCES geo.Districts (Id) ON DELETE NO ACTION
);

CREATE TABLE tenants.TenantRolePermissions (
    Id uuid NOT NULL,
    TenantId uuid NOT NULL,
    TenantRoleId uuid NOT NULL,
    PermissionId uuid NOT NULL,
    IsDeleted boolean NOT NULL DEFAULT CAST(0 AS boolean),
    CreatedAt datetime NOT NULL,
    CreatedByUserId uuid NULL,
    UpdatedAt datetime NULL,
    UpdatedByUserId uuid NULL,
    varbinary(8) varbinary(8) NOT NULL,
    CONSTRAINT PK_TenantRolePermissions PRIMARY KEY (Id),
    CONSTRAINT FK_TenantRolePermissions_Permissions_PermissionId FOREIGN KEY (PermissionId) REFERENCES auth.Permissions (Id) ON DELETE NO ACTION,
    CONSTRAINT FK_TenantRolePermissions_TenantRoles_TenantRoleId FOREIGN KEY (TenantRoleId) REFERENCES tenants.TenantRoles (Id) ON DELETE NO ACTION,
    CONSTRAINT FK_TenantRolePermissions_Tenants_TenantId FOREIGN KEY (TenantId) REFERENCES tenants.Tenants (Id) ON DELETE NO ACTION
);

CREATE TABLE tenants.TenantUserRoles (
    Id uuid NOT NULL,
    TenantId uuid NOT NULL,
    TenantRoleId uuid NOT NULL,
    UserId uuid NOT NULL,
    IsDeleted boolean NOT NULL DEFAULT CAST(0 AS boolean),
    CreatedAt datetime NOT NULL,
    CreatedByUserId uuid NULL,
    UpdatedAt datetime NULL,
    UpdatedByUserId uuid NULL,
    varbinary(8) varbinary(8) NOT NULL,
    CONSTRAINT PK_TenantUserRoles PRIMARY KEY (Id),
    CONSTRAINT FK_TenantUserRoles_AspNetUsers_UserId FOREIGN KEY (UserId) REFERENCES AspNetUsers (Id) ON DELETE NO ACTION,
    CONSTRAINT FK_TenantUserRoles_TenantRoles_TenantRoleId FOREIGN KEY (TenantRoleId) REFERENCES tenants.TenantRoles (Id) ON DELETE NO ACTION,
    CONSTRAINT FK_TenantUserRoles_Tenants_TenantId FOREIGN KEY (TenantId) REFERENCES tenants.Tenants (Id) ON DELETE NO ACTION
);

CREATE TABLE tours.TourItineraryItems (
    Id uuid NOT NULL,
    TenantId uuid NOT NULL,
    TourItineraryDayId uuid NOT NULL,
    Type int NOT NULL,
    Title varchar(300) NOT NULL,
    ShortDescription varchar(2000) NULL,
    DescriptionMarkdown text NULL,
    DescriptionHtml text NULL,
    StartTime time NULL,
    EndTime time NULL,
    LocationName varchar(300) NULL,
    AddressLine varchar(500) NULL,
    TransportationMode varchar(100) NULL,
    IncludesTicket boolean NOT NULL,
    IncludesMeal boolean NOT NULL,
    IsOptional boolean NOT NULL,
    RequiresAdditionalFee boolean NOT NULL,
    Notes varchar(2000) NULL,
    MetadataJson text NULL,
    SortOrder int NOT NULL,
    IsActive boolean NOT NULL,
    IsDeleted boolean NOT NULL,
    CreatedAt datetime NOT NULL,
    CreatedByUserId uuid NULL,
    UpdatedAt datetime NULL,
    UpdatedByUserId uuid NULL,
    varbinary(8) varbinary(8) NOT NULL,
    CONSTRAINT PK_TourItineraryItems PRIMARY KEY (Id),
    CONSTRAINT FK_TourItineraryItems_TourItineraryDays_TourItineraryDayId FOREIGN KEY (TourItineraryDayId) REFERENCES tours.TourItineraryDays (Id) ON DELETE NO ACTION
);

CREATE TABLE tours.TourScheduleAddonPrices (
    Id uuid NOT NULL,
    TenantId uuid NOT NULL,
    TourScheduleId uuid NOT NULL,
    TourAddonId uuid NOT NULL,
    CurrencyCode varchar(10) NOT NULL,
    Price decimal(18,2) NULL,
    OriginalPrice decimal(18,2) NULL,
    IsPerPerson boolean NOT NULL,
    IsRequired boolean NOT NULL,
    IsDefaultSelected boolean NOT NULL,
    AllowQuantitySelection boolean NOT NULL,
    MinQuantity int NULL,
    MaxQuantity int NULL,
    Notes varchar(2000) NULL,
    MetadataJson text NULL,
    SortOrder int NOT NULL,
    IsActive boolean NOT NULL,
    IsDeleted boolean NOT NULL,
    CreatedAt datetime NOT NULL,
    CreatedByUserId uuid NULL,
    UpdatedAt datetime NULL,
    UpdatedByUserId uuid NULL,
    varbinary(8) varbinary(8) NOT NULL,
    CONSTRAINT PK_TourScheduleAddonPrices PRIMARY KEY (Id),
    CONSTRAINT FK_TourScheduleAddonPrices_TourAddons_TourAddonId FOREIGN KEY (TourAddonId) REFERENCES tours.TourAddons (Id) ON DELETE NO ACTION,
    CONSTRAINT FK_TourScheduleAddonPrices_TourSchedules_TourScheduleId FOREIGN KEY (TourScheduleId) REFERENCES tours.TourSchedules (Id) ON DELETE NO ACTION
);

CREATE TABLE tours.TourScheduleCapacities (
    Id uuid NOT NULL,
    TenantId uuid NOT NULL,
    TourScheduleId uuid NOT NULL,
    TotalSlots int NOT NULL,
    SoldSlots int NOT NULL,
    HeldSlots int NOT NULL,
    BlockedSlots int NOT NULL,
    MinGuestsToOperate int NULL,
    MaxGuestsPerBooking int NULL,
    WarningThreshold int NULL,
    Status int NOT NULL,
    AllowWaitlist boolean NOT NULL,
    AutoCloseWhenFull boolean NOT NULL,
    Notes varchar(2000) NULL,
    MetadataJson text NULL,
    IsActive boolean NOT NULL,
    IsDeleted boolean NOT NULL,
    CreatedAt datetime NOT NULL,
    CreatedByUserId uuid NULL,
    UpdatedAt datetime NULL,
    UpdatedByUserId uuid NULL,
    varbinary(8) varbinary(8) NOT NULL,
    CONSTRAINT PK_TourScheduleCapacities PRIMARY KEY (Id),
    CONSTRAINT FK_TourScheduleCapacities_TourSchedules_TourScheduleId FOREIGN KEY (TourScheduleId) REFERENCES tours.TourSchedules (Id) ON DELETE NO ACTION
);

CREATE TABLE tours.TourSchedulePrices (
    Id uuid NOT NULL,
    TenantId uuid NOT NULL,
    TourScheduleId uuid NOT NULL,
    PriceType int NOT NULL,
    CurrencyCode varchar(10) NOT NULL,
    Price decimal(18,2) NOT NULL,
    OriginalPrice decimal(18,2) NULL,
    Taxes decimal(18,2) NULL,
    Fees decimal(18,2) NULL,
    MinAge int NULL,
    MaxAge int NULL,
    MinQuantity int NULL,
    MaxQuantity int NULL,
    IsDefault boolean NOT NULL,
    IsIncludedTax boolean NOT NULL,
    IsIncludedFee boolean NOT NULL,
    Label varchar(200) NULL,
    Notes varchar(2000) NULL,
    MetadataJson text NULL,
    IsActive boolean NOT NULL,
    IsDeleted boolean NOT NULL,
    CreatedAt datetime NOT NULL,
    CreatedByUserId uuid NULL,
    UpdatedAt datetime NULL,
    UpdatedByUserId uuid NULL,
    varbinary(8) varbinary(8) NOT NULL,
    CONSTRAINT PK_TourSchedulePrices PRIMARY KEY (Id),
    CONSTRAINT FK_TourSchedulePrices_TourSchedules_TourScheduleId FOREIGN KEY (TourScheduleId) REFERENCES tours.TourSchedules (Id) ON DELETE NO ACTION
);

CREATE TABLE hotels.RatePlanPolicies (
    Id uuid NOT NULL,
    TenantId uuid NOT NULL,
    RatePlanId uuid NOT NULL,
    PolicyJson text NULL,
    IsActive boolean NOT NULL,
    IsDeleted boolean NOT NULL,
    CreatedAt datetime NOT NULL,
    CreatedByUserId uuid NULL,
    UpdatedAt datetime NULL,
    UpdatedByUserId uuid NULL,
    varbinary(8) varbinary(8) NOT NULL,
    CONSTRAINT PK_RatePlanPolicies PRIMARY KEY (Id),
    CONSTRAINT FK_RatePlanPolicies_RatePlans_RatePlanId FOREIGN KEY (RatePlanId) REFERENCES hotels.RatePlans (Id) ON DELETE NO ACTION
);

CREATE TABLE hotels.RatePlanRoomTypes (
    Id uuid NOT NULL,
    TenantId uuid NOT NULL,
    RatePlanId uuid NOT NULL,
    RoomTypeId uuid NOT NULL,
    BasePrice decimal(18,2) NULL,
    CurrencyCode varchar(10) NOT NULL,
    IsActive boolean NOT NULL,
    IsDeleted boolean NOT NULL,
    CreatedAt datetime NOT NULL,
    CreatedByUserId uuid NULL,
    UpdatedAt datetime NULL,
    UpdatedByUserId uuid NULL,
    varbinary(8) varbinary(8) NOT NULL,
    CONSTRAINT PK_RatePlanRoomTypes PRIMARY KEY (Id),
    CONSTRAINT FK_RatePlanRoomTypes_RatePlans_RatePlanId FOREIGN KEY (RatePlanId) REFERENCES hotels.RatePlans (Id) ON DELETE NO ACTION,
    CONSTRAINT FK_RatePlanRoomTypes_RoomTypes_RoomTypeId FOREIGN KEY (RoomTypeId) REFERENCES hotels.RoomTypes (Id) ON DELETE NO ACTION
);

CREATE TABLE catalog.Locations (
    Id uuid NOT NULL,
    TenantId uuid NOT NULL,
    Type int NOT NULL,
    Name varchar(200) NOT NULL,
    NormalizedName varchar(250) NOT NULL,
    ShortName varchar(100) NULL,
    Code varchar(50) NULL,
    AirportIataCode varchar(10) NULL,
    AirportIcaoCode varchar(10) NULL,
    TrainStationCode varchar(50) NULL,
    BusStationCode varchar(50) NULL,
    TimeZone varchar(64) NULL,
    AddressLine varchar(300) NULL,
    ProvinceId uuid NULL,
    DistrictId uuid NULL,
    WardId uuid NULL,
    Latitude float NULL,
    Longitude float NULL,
    MetadataJson text NULL,
    IsActive boolean NOT NULL DEFAULT CAST(1 AS boolean),
    IsDeleted boolean NOT NULL DEFAULT CAST(0 AS boolean),
    CreatedAt datetime NOT NULL,
    CreatedByUserId uuid NULL,
    UpdatedAt datetime NULL,
    UpdatedByUserId uuid NULL,
    varbinary(8) blob NOT NULL,
    CONSTRAINT PK_Locations PRIMARY KEY (Id),
    CONSTRAINT FK_Locations_Districts_DistrictId FOREIGN KEY (DistrictId) REFERENCES geo.Districts (Id) ON DELETE NO ACTION,
    CONSTRAINT FK_Locations_Provinces_ProvinceId FOREIGN KEY (ProvinceId) REFERENCES geo.Provinces (Id) ON DELETE NO ACTION,
    CONSTRAINT FK_Locations_Wards_WardId FOREIGN KEY (WardId) REFERENCES geo.Wards (Id) ON DELETE NO ACTION
);

CREATE TABLE hotels.DailyRates (
    Id uuid NOT NULL,
    TenantId uuid NOT NULL,
    RatePlanRoomTypeId uuid NOT NULL,
    Date date NOT NULL,
    Price decimal(18,2) NOT NULL,
    CurrencyCode varchar(10) NOT NULL,
    BasePrice decimal(18,2) NULL,
    Taxes decimal(18,2) NULL,
    Fees decimal(18,2) NULL,
    IsActive boolean NOT NULL,
    MetadataJson text NULL,
    IsDeleted boolean NOT NULL,
    CreatedAt datetime NOT NULL,
    CreatedByUserId uuid NULL,
    UpdatedAt datetime NULL,
    UpdatedByUserId uuid NULL,
    varbinary(8) varbinary(8) NOT NULL,
    CONSTRAINT PK_DailyRates PRIMARY KEY (Id),
    CONSTRAINT FK_DailyRates_RatePlanRoomTypes_RatePlanRoomTypeId FOREIGN KEY (RatePlanRoomTypeId) REFERENCES hotels.RatePlanRoomTypes (Id) ON DELETE NO ACTION
);

CREATE TABLE hotels.PromoRateOverrides (
    Id uuid NOT NULL,
    TenantId uuid NOT NULL,
    RatePlanRoomTypeId uuid NOT NULL,
    PromoCodeId uuid NULL,
    PromoCode varchar(80) NULL,
    StartDate date NOT NULL,
    EndDate date NOT NULL,
    OverridePrice decimal(18,2) NULL,
    DiscountPercent decimal(5,2) NULL,
    CurrencyCode varchar(10) NOT NULL,
    ConditionsJson text NULL,
    IsActive boolean NOT NULL,
    IsDeleted boolean NOT NULL,
    CreatedAt datetime NOT NULL,
    CreatedByUserId uuid NULL,
    UpdatedAt datetime NULL,
    UpdatedByUserId uuid NULL,
    varbinary(8) varbinary(8) NOT NULL,
    CONSTRAINT PK_PromoRateOverrides PRIMARY KEY (Id),
    CONSTRAINT FK_PromoRateOverrides_RatePlanRoomTypes_RatePlanRoomTypeId FOREIGN KEY (RatePlanRoomTypeId) REFERENCES hotels.RatePlanRoomTypes (Id) ON DELETE NO ACTION
);

CREATE TABLE flight.Airports (
    Id uuid NOT NULL DEFAULT (NEWSEQUENTIALID()),
    TenantId uuid NOT NULL,
    LocationId uuid NOT NULL,
    Name varchar(200) NOT NULL,
    Code varchar(50) NOT NULL,
    IataCode varchar(8) NULL,
    IcaoCode varchar(8) NULL,
    TimeZone varchar(64) NULL,
    Latitude float NULL,
    Longitude float NULL,
    IsActive boolean NOT NULL DEFAULT CAST(1 AS boolean),
    IsDeleted boolean NOT NULL DEFAULT CAST(0 AS boolean),
    CreatedAt datetime NOT NULL DEFAULT (SWITCHOFFSET(SYSDATETIMEOFFSET(), '+07:00')),
    CreatedByUserId uuid NULL,
    UpdatedAt datetime NULL,
    UpdatedByUserId uuid NULL,
    varbinary(8) varbinary(8) NOT NULL,
    CONSTRAINT PK_Airports PRIMARY KEY (Id),
    CONSTRAINT FK_Airports_Locations_LocationId FOREIGN KEY (LocationId) REFERENCES catalog.Locations (Id) ON DELETE NO ACTION
);

CREATE TABLE catalog.Providers (
    Id uuid NOT NULL,
    TenantId uuid NOT NULL,
    Type int NOT NULL,
    Code varchar(50) NOT NULL,
    Name varchar(200) NOT NULL,
    Slug varchar(200) NOT NULL,
    LegalName varchar(250) NULL,
    LogoUrl varchar(500) NULL,
    CoverUrl varchar(500) NULL,
    SupportPhone varchar(50) NULL,
    SupportEmail varchar(200) NULL,
    WebsiteUrl varchar(300) NULL,
    AddressLine varchar(300) NULL,
    LocationId uuid NULL,
    ProvinceId uuid NULL,
    DistrictId uuid NULL,
    WardId uuid NULL,
    RatingAverage decimal(3,2) NULL,
    RatingCount int NOT NULL DEFAULT 0,
    Description text NULL,
    MetadataJson text NULL,
    IsActive boolean NOT NULL DEFAULT CAST(1 AS boolean),
    IsDeleted boolean NOT NULL DEFAULT CAST(0 AS boolean),
    CreatedAt datetime NOT NULL,
    CreatedByUserId uuid NULL,
    UpdatedAt datetime NULL,
    UpdatedByUserId uuid NULL,
    varbinary(8) blob NOT NULL,
    CONSTRAINT PK_Providers PRIMARY KEY (Id),
    CONSTRAINT FK_Providers_Districts_DistrictId FOREIGN KEY (DistrictId) REFERENCES geo.Districts (Id) ON DELETE NO ACTION,
    CONSTRAINT FK_Providers_Locations_LocationId FOREIGN KEY (LocationId) REFERENCES catalog.Locations (Id) ON DELETE NO ACTION,
    CONSTRAINT FK_Providers_Provinces_ProvinceId FOREIGN KEY (ProvinceId) REFERENCES geo.Provinces (Id) ON DELETE NO ACTION,
    CONSTRAINT FK_Providers_Wards_WardId FOREIGN KEY (WardId) REFERENCES geo.Wards (Id) ON DELETE NO ACTION
);

CREATE TABLE bus.StopPoints (
    Id uuid NOT NULL,
    TenantId uuid NOT NULL,
    LocationId uuid NOT NULL,
    Type int NOT NULL,
    Name varchar(200) NOT NULL,
    AddressLine varchar(300) NULL,
    Latitude float NULL,
    Longitude float NULL,
    Notes text NULL,
    SortOrder int NOT NULL DEFAULT 0,
    IsActive boolean NOT NULL DEFAULT CAST(1 AS boolean),
    IsDeleted boolean NOT NULL DEFAULT CAST(0 AS boolean),
    CreatedAt datetime NOT NULL,
    CreatedByUserId uuid NULL,
    UpdatedAt datetime NULL,
    UpdatedByUserId uuid NULL,
    varbinary(8) blob NOT NULL,
    CONSTRAINT PK_StopPoints PRIMARY KEY (Id),
    CONSTRAINT FK_StopPoints_Locations_LocationId FOREIGN KEY (LocationId) REFERENCES catalog.Locations (Id) ON DELETE NO ACTION
);

CREATE TABLE train.StopPoints (
    Id uuid NOT NULL,
    TenantId uuid NOT NULL,
    LocationId uuid NOT NULL,
    Type int NOT NULL,
    Name varchar(200) NOT NULL,
    AddressLine varchar(300) NULL,
    Latitude float NULL,
    Longitude float NULL,
    Notes text NULL,
    SortOrder int NOT NULL DEFAULT 0,
    IsActive boolean NOT NULL DEFAULT CAST(1 AS boolean),
    IsDeleted boolean NOT NULL DEFAULT CAST(0 AS boolean),
    CreatedAt datetime NOT NULL,
    CreatedByUserId uuid NULL,
    UpdatedAt datetime NULL,
    UpdatedByUserId uuid NULL,
    varbinary(8) blob NOT NULL,
    CONSTRAINT PK_StopPoints PRIMARY KEY (Id),
    CONSTRAINT FK_StopPoints_Locations_LocationId FOREIGN KEY (LocationId) REFERENCES catalog.Locations (Id) ON DELETE NO ACTION
);

CREATE TABLE flight.Flights (
    Id uuid NOT NULL DEFAULT (NEWSEQUENTIALID()),
    TenantId uuid NOT NULL,
    AirlineId uuid NOT NULL,
    AircraftId uuid NOT NULL,
    FromAirportId uuid NOT NULL,
    ToAirportId uuid NOT NULL,
    FlightNumber varchar(20) NOT NULL,
    DepartureAt datetime NOT NULL,
    ArrivalAt datetime NOT NULL,
    Status int NOT NULL,
    IsActive boolean NOT NULL DEFAULT CAST(1 AS boolean),
    Notes varchar(2000) NULL,
    IsDeleted boolean NOT NULL DEFAULT CAST(0 AS boolean),
    CreatedAt datetime NOT NULL DEFAULT (SWITCHOFFSET(SYSDATETIMEOFFSET(), '+07:00')),
    CreatedByUserId uuid NULL,
    UpdatedAt datetime NULL,
    UpdatedByUserId uuid NULL,
    varbinary(8) varbinary(8) NOT NULL,
    CONSTRAINT PK_Flights PRIMARY KEY (Id),
    CONSTRAINT FK_Flights_Aircrafts_AircraftId FOREIGN KEY (AircraftId) REFERENCES flight.Aircrafts (Id) ON DELETE NO ACTION,
    CONSTRAINT FK_Flights_Airlines_AirlineId FOREIGN KEY (AirlineId) REFERENCES flight.Airlines (Id) ON DELETE NO ACTION,
    CONSTRAINT FK_Flights_Airports_FromAirportId FOREIGN KEY (FromAirportId) REFERENCES flight.Airports (Id) ON DELETE NO ACTION,
    CONSTRAINT FK_Flights_Airports_ToAirportId FOREIGN KEY (ToAirportId) REFERENCES flight.Airports (Id) ON DELETE NO ACTION
);

CREATE TABLE fleet.Vehicles (
    Id uuid NOT NULL,
    TenantId uuid NOT NULL,
    VehicleType int NOT NULL,
    ProviderId uuid NOT NULL,
    VehicleModelId uuid NULL,
    SeatMapId uuid NULL,
    Code varchar(50) NOT NULL,
    Name varchar(200) NOT NULL,
    PlateNumber varchar(50) NULL,
    RegistrationNumber varchar(50) NULL,
    SeatCapacity int NOT NULL,
    InServiceFrom datetime NULL,
    InServiceTo datetime NULL,
    Status varchar(50) NULL,
    IsActive boolean NOT NULL DEFAULT CAST(1 AS boolean),
    MetadataJson text NULL,
    IsDeleted boolean NOT NULL DEFAULT CAST(0 AS boolean),
    CreatedAt datetime NOT NULL,
    CreatedByUserId uuid NULL,
    UpdatedAt datetime NULL,
    UpdatedByUserId uuid NULL,
    varbinary(8) blob NOT NULL,
    CONSTRAINT PK_Vehicles PRIMARY KEY (Id),
    CONSTRAINT FK_Vehicles_Providers_ProviderId FOREIGN KEY (ProviderId) REFERENCES catalog.Providers (Id) ON DELETE NO ACTION,
    CONSTRAINT FK_Vehicles_SeatMaps_SeatMapId FOREIGN KEY (SeatMapId) REFERENCES fleet.SeatMaps (Id) ON DELETE NO ACTION,
    CONSTRAINT FK_Vehicles_VehicleModels_VehicleModelId FOREIGN KEY (VehicleModelId) REFERENCES fleet.VehicleModels (Id) ON DELETE NO ACTION
);

CREATE TABLE bus.Routes (
    Id uuid NOT NULL,
    TenantId uuid NOT NULL,
    ProviderId uuid NOT NULL,
    Code varchar(50) NOT NULL,
    Name varchar(200) NOT NULL,
    FromStopPointId uuid NOT NULL,
    ToStopPointId uuid NOT NULL,
    EstimatedMinutes int NOT NULL DEFAULT 0,
    DistanceKm int NOT NULL DEFAULT 0,
    IsActive boolean NOT NULL DEFAULT CAST(1 AS boolean),
    IsDeleted boolean NOT NULL DEFAULT CAST(0 AS boolean),
    CreatedAt datetime NOT NULL,
    CreatedByUserId uuid NULL,
    UpdatedAt datetime NULL,
    UpdatedByUserId uuid NULL,
    varbinary(8) blob NOT NULL,
    CONSTRAINT PK_Routes PRIMARY KEY (Id),
    CONSTRAINT FK_Routes_Providers_ProviderId FOREIGN KEY (ProviderId) REFERENCES catalog.Providers (Id) ON DELETE NO ACTION,
    CONSTRAINT FK_Routes_StopPoints_FromStopPointId FOREIGN KEY (FromStopPointId) REFERENCES bus.StopPoints (Id) ON DELETE NO ACTION,
    CONSTRAINT FK_Routes_StopPoints_ToStopPointId FOREIGN KEY (ToStopPointId) REFERENCES bus.StopPoints (Id) ON DELETE NO ACTION
);

CREATE TABLE train.Routes (
    Id uuid NOT NULL,
    TenantId uuid NOT NULL,
    ProviderId uuid NOT NULL,
    Code varchar(50) NOT NULL,
    Name varchar(200) NOT NULL,
    FromStopPointId uuid NOT NULL,
    ToStopPointId uuid NOT NULL,
    EstimatedMinutes int NOT NULL DEFAULT 0,
    DistanceKm int NOT NULL DEFAULT 0,
    IsActive boolean NOT NULL DEFAULT CAST(1 AS boolean),
    IsDeleted boolean NOT NULL DEFAULT CAST(0 AS boolean),
    CreatedAt datetime NOT NULL,
    CreatedByUserId uuid NULL,
    UpdatedAt datetime NULL,
    UpdatedByUserId uuid NULL,
    varbinary(8) blob NOT NULL,
    CONSTRAINT PK_Routes PRIMARY KEY (Id),
    CONSTRAINT FK_Routes_StopPoints_FromStopPointId FOREIGN KEY (FromStopPointId) REFERENCES train.StopPoints (Id) ON DELETE NO ACTION,
    CONSTRAINT FK_Routes_StopPoints_ToStopPointId FOREIGN KEY (ToStopPointId) REFERENCES train.StopPoints (Id) ON DELETE NO ACTION
);

CREATE TABLE flight.Offers (
    Id uuid NOT NULL DEFAULT (NEWSEQUENTIALID()),
    TenantId uuid NOT NULL,
    AirlineId uuid NOT NULL,
    FlightId uuid NOT NULL,
    FareClassId uuid NOT NULL,
    Status int NOT NULL,
    CurrencyCode char(3) NOT NULL,
    BaseFare decimal(18,2) NOT NULL,
    TaxesFees decimal(18,2) NOT NULL,
    TotalPrice decimal(18,2) NOT NULL,
    SeatsAvailable int NOT NULL DEFAULT 9,
    RequestedAt datetime NOT NULL,
    ExpiresAt datetime NOT NULL,
    ConditionsJson text NULL,
    MetadataJson text NULL,
    IsDeleted boolean NOT NULL DEFAULT CAST(0 AS boolean),
    CreatedAt datetime NOT NULL DEFAULT (SWITCHOFFSET(SYSDATETIMEOFFSET(), '+07:00')),
    CreatedByUserId uuid NULL,
    UpdatedAt datetime NULL,
    UpdatedByUserId uuid NULL,
    varbinary(8) varbinary(8) NOT NULL,
    CONSTRAINT PK_Offers PRIMARY KEY (Id),
    CONSTRAINT CK_flight_Offers_ExpiresAt CHECK (ExpiresAt > RequestedAt),
    CONSTRAINT CK_flight_Offers_TotalPrice CHECK (TotalPrice >= 0),
    CONSTRAINT FK_Offers_Airlines_AirlineId FOREIGN KEY (AirlineId) REFERENCES flight.Airlines (Id) ON DELETE NO ACTION,
    CONSTRAINT FK_Offers_FareClasses_FareClassId FOREIGN KEY (FareClassId) REFERENCES flight.FareClasses (Id) ON DELETE NO ACTION,
    CONSTRAINT FK_Offers_Flights_FlightId FOREIGN KEY (FlightId) REFERENCES flight.Flights (Id) ON DELETE NO ACTION
);

CREATE TABLE fleet.BusVehicleDetails (
    Id uuid NOT NULL,
    TenantId uuid NOT NULL,
    VehicleId uuid NOT NULL,
    BusType varchar(100) NULL,
    AmenitiesJson text NULL,
    IsDeleted boolean NOT NULL DEFAULT CAST(0 AS boolean),
    CreatedAt datetime NOT NULL,
    CreatedByUserId uuid NULL,
    UpdatedAt datetime NULL,
    UpdatedByUserId uuid NULL,
    varbinary(8) blob NOT NULL,
    CONSTRAINT PK_BusVehicleDetails PRIMARY KEY (Id),
    CONSTRAINT FK_BusVehicleDetails_Vehicles_VehicleId FOREIGN KEY (VehicleId) REFERENCES fleet.Vehicles (Id) ON DELETE NO ACTION
);

CREATE TABLE bus.RouteStops (
    Id uuid NOT NULL,
    TenantId uuid NOT NULL,
    RouteId uuid NOT NULL,
    StopPointId uuid NOT NULL,
    StopIndex int NOT NULL,
    DistanceFromStartKm int NULL,
    MinutesFromStart int NULL,
    IsActive boolean NOT NULL DEFAULT CAST(1 AS boolean),
    IsDeleted boolean NOT NULL DEFAULT CAST(0 AS boolean),
    CreatedAt datetime NOT NULL,
    CreatedByUserId uuid NULL,
    UpdatedAt datetime NULL,
    UpdatedByUserId uuid NULL,
    varbinary(8) blob NOT NULL,
    CONSTRAINT PK_RouteStops PRIMARY KEY (Id),
    CONSTRAINT FK_RouteStops_Routes_RouteId FOREIGN KEY (RouteId) REFERENCES bus.Routes (Id) ON DELETE NO ACTION,
    CONSTRAINT FK_RouteStops_StopPoints_StopPointId FOREIGN KEY (StopPointId) REFERENCES bus.StopPoints (Id) ON DELETE NO ACTION
);

CREATE TABLE bus.Trips (
    Id uuid NOT NULL,
    TenantId uuid NOT NULL,
    ProviderId uuid NOT NULL,
    RouteId uuid NOT NULL,
    VehicleId uuid NOT NULL,
    Code varchar(50) NOT NULL,
    Name varchar(200) NOT NULL,
    Status int NOT NULL,
    DepartureAt datetime NOT NULL,
    ArrivalAt datetime NOT NULL,
    FareRulesJson text NULL,
    BaggagePolicyJson text NULL,
    BoardingPolicyJson text NULL,
    Notes text NULL,
    IsActive boolean NOT NULL DEFAULT CAST(1 AS boolean),
    IsDeleted boolean NOT NULL DEFAULT CAST(0 AS boolean),
    CreatedAt datetime NOT NULL,
    CreatedByUserId uuid NULL,
    UpdatedAt datetime NULL,
    UpdatedByUserId uuid NULL,
    varbinary(8) blob NOT NULL,
    CONSTRAINT PK_Trips PRIMARY KEY (Id),
    CONSTRAINT FK_Trips_Providers_ProviderId FOREIGN KEY (ProviderId) REFERENCES catalog.Providers (Id) ON DELETE NO ACTION,
    CONSTRAINT FK_Trips_Routes_RouteId FOREIGN KEY (RouteId) REFERENCES bus.Routes (Id) ON DELETE NO ACTION,
    CONSTRAINT FK_Trips_Vehicles_VehicleId FOREIGN KEY (VehicleId) REFERENCES fleet.Vehicles (Id) ON DELETE NO ACTION
);

CREATE TABLE train.RouteStops (
    Id uuid NOT NULL,
    TenantId uuid NOT NULL,
    RouteId uuid NOT NULL,
    StopPointId uuid NOT NULL,
    StopIndex int NOT NULL,
    DistanceFromStartKm int NULL,
    MinutesFromStart int NULL,
    IsActive boolean NOT NULL DEFAULT CAST(1 AS boolean),
    IsDeleted boolean NOT NULL DEFAULT CAST(0 AS boolean),
    CreatedAt datetime NOT NULL,
    CreatedByUserId uuid NULL,
    UpdatedAt datetime NULL,
    UpdatedByUserId uuid NULL,
    varbinary(8) blob NOT NULL,
    CONSTRAINT PK_RouteStops PRIMARY KEY (Id),
    CONSTRAINT FK_RouteStops_Routes_RouteId FOREIGN KEY (RouteId) REFERENCES train.Routes (Id) ON DELETE NO ACTION,
    CONSTRAINT FK_RouteStops_StopPoints_StopPointId FOREIGN KEY (StopPointId) REFERENCES train.StopPoints (Id) ON DELETE NO ACTION
);

CREATE TABLE train.Trips (
    Id uuid NOT NULL,
    TenantId uuid NOT NULL,
    ProviderId uuid NOT NULL,
    RouteId uuid NOT NULL,
    TrainNumber varchar(20) NOT NULL,
    Code varchar(50) NOT NULL,
    Name varchar(200) NOT NULL,
    Status int NOT NULL,
    DepartureAt datetime NOT NULL,
    ArrivalAt datetime NOT NULL,
    FareRulesJson text NULL,
    BaggagePolicyJson text NULL,
    BoardingPolicyJson text NULL,
    IsActive boolean NOT NULL DEFAULT CAST(1 AS boolean),
    IsDeleted boolean NOT NULL DEFAULT CAST(0 AS boolean),
    CreatedAt datetime NOT NULL,
    CreatedByUserId uuid NULL,
    UpdatedAt datetime NULL,
    UpdatedByUserId uuid NULL,
    varbinary(8) blob NOT NULL,
    CONSTRAINT PK_Trips PRIMARY KEY (Id),
    CONSTRAINT FK_Trips_Routes_RouteId FOREIGN KEY (RouteId) REFERENCES train.Routes (Id) ON DELETE NO ACTION
);

CREATE TABLE flight.OfferSegments (
    Id uuid NOT NULL DEFAULT (NEWSEQUENTIALID()),
    TenantId uuid NOT NULL,
    OfferId uuid NOT NULL,
    SegmentIndex int NOT NULL,
    FromAirportId uuid NOT NULL,
    ToAirportId uuid NOT NULL,
    DepartureAt datetime NOT NULL,
    ArrivalAt datetime NOT NULL,
    FlightNumber varchar(20) NULL,
    IsDeleted boolean NOT NULL DEFAULT CAST(0 AS boolean),
    CreatedAt datetime NOT NULL DEFAULT (SWITCHOFFSET(SYSDATETIMEOFFSET(), '+07:00')),
    CreatedByUserId uuid NULL,
    UpdatedAt datetime NULL,
    UpdatedByUserId uuid NULL,
    varbinary(8) varbinary(8) NOT NULL,
    CONSTRAINT PK_OfferSegments PRIMARY KEY (Id),
    CONSTRAINT FK_OfferSegments_Airports_FromAirportId FOREIGN KEY (FromAirportId) REFERENCES flight.Airports (Id) ON DELETE NO ACTION,
    CONSTRAINT FK_OfferSegments_Airports_ToAirportId FOREIGN KEY (ToAirportId) REFERENCES flight.Airports (Id) ON DELETE NO ACTION,
    CONSTRAINT FK_OfferSegments_Offers_OfferId FOREIGN KEY (OfferId) REFERENCES flight.Offers (Id) ON DELETE NO ACTION
);

CREATE TABLE flight.OfferTaxFeeLines (
    Id uuid NOT NULL DEFAULT (NEWSEQUENTIALID()),
    TenantId uuid NOT NULL,
    OfferId uuid NOT NULL,
    LineType int NOT NULL,
    Code varchar(50) NOT NULL,
    Name varchar(200) NOT NULL,
    CurrencyCode char(3) NOT NULL,
    Amount decimal(18,2) NOT NULL,
    SortOrder int NOT NULL DEFAULT 0,
    IsDeleted boolean NOT NULL DEFAULT CAST(0 AS boolean),
    CreatedAt datetime NOT NULL DEFAULT (SWITCHOFFSET(SYSDATETIMEOFFSET(), '+07:00')),
    CreatedByUserId uuid NULL,
    UpdatedAt datetime NULL,
    UpdatedByUserId uuid NULL,
    varbinary(8) varbinary(8) NOT NULL,
    CONSTRAINT PK_OfferTaxFeeLines PRIMARY KEY (Id),
    CONSTRAINT FK_OfferTaxFeeLines_Offers_OfferId FOREIGN KEY (OfferId) REFERENCES flight.Offers (Id) ON DELETE NO ACTION
);

CREATE TABLE bus.TripStopTimes (
    Id uuid NOT NULL,
    TenantId uuid NOT NULL,
    TripId uuid NOT NULL,
    StopPointId uuid NOT NULL,
    StopIndex int NOT NULL,
    ArriveAt datetime NULL,
    DepartAt datetime NULL,
    MinutesFromStart int NULL,
    IsActive boolean NOT NULL DEFAULT CAST(1 AS boolean),
    IsDeleted boolean NOT NULL DEFAULT CAST(0 AS boolean),
    CreatedAt datetime NOT NULL,
    CreatedByUserId uuid NULL,
    UpdatedAt datetime NULL,
    UpdatedByUserId uuid NULL,
    varbinary(8) blob NOT NULL,
    CONSTRAINT PK_TripStopTimes PRIMARY KEY (Id),
    CONSTRAINT FK_TripStopTimes_StopPoints_StopPointId FOREIGN KEY (StopPointId) REFERENCES bus.StopPoints (Id) ON DELETE NO ACTION,
    CONSTRAINT FK_TripStopTimes_Trips_TripId FOREIGN KEY (TripId) REFERENCES bus.Trips (Id) ON DELETE NO ACTION
);

CREATE TABLE train.TrainCars (
    Id uuid NOT NULL,
    TenantId uuid NOT NULL,
    TripId uuid NOT NULL,
    CarNumber varchar(20) NOT NULL,
    CarType int NOT NULL,
    CabinClass varchar(50) NULL,
    SortOrder int NOT NULL DEFAULT 0,
    IsActive boolean NOT NULL DEFAULT CAST(1 AS boolean),
    IsDeleted boolean NOT NULL DEFAULT CAST(0 AS boolean),
    CreatedAt datetime NOT NULL,
    CreatedByUserId uuid NULL,
    UpdatedAt datetime NULL,
    UpdatedByUserId uuid NULL,
    varbinary(8) blob NOT NULL,
    CONSTRAINT PK_TrainCars PRIMARY KEY (Id),
    CONSTRAINT FK_TrainCars_Trips_TripId FOREIGN KEY (TripId) REFERENCES train.Trips (Id) ON DELETE NO ACTION
);

CREATE TABLE train.TripStopTimes (
    Id uuid NOT NULL,
    TenantId uuid NOT NULL,
    TripId uuid NOT NULL,
    StopPointId uuid NOT NULL,
    StopIndex int NOT NULL,
    ArriveAt datetime NULL,
    DepartAt datetime NULL,
    MinutesFromStart int NULL,
    IsActive boolean NOT NULL DEFAULT CAST(1 AS boolean),
    IsDeleted boolean NOT NULL DEFAULT CAST(0 AS boolean),
    CreatedAt datetime NOT NULL,
    CreatedByUserId uuid NULL,
    UpdatedAt datetime NULL,
    UpdatedByUserId uuid NULL,
    varbinary(8) blob NOT NULL,
    CONSTRAINT PK_TripStopTimes PRIMARY KEY (Id),
    CONSTRAINT FK_TripStopTimes_StopPoints_StopPointId FOREIGN KEY (StopPointId) REFERENCES train.StopPoints (Id) ON DELETE NO ACTION,
    CONSTRAINT FK_TripStopTimes_Trips_TripId FOREIGN KEY (TripId) REFERENCES train.Trips (Id) ON DELETE NO ACTION
);

CREATE TABLE bus.TripSeatHolds (
    Id uuid NOT NULL,
    TenantId uuid NOT NULL,
    TripId uuid NOT NULL,
    SeatId uuid NOT NULL,
    FromTripStopTimeId uuid NOT NULL,
    ToTripStopTimeId uuid NOT NULL,
    FromStopIndex int NOT NULL,
    ToStopIndex int NOT NULL,
    Status int NOT NULL,
    UserId uuid NULL,
    BookingId uuid NULL,
    HoldToken varchar(100) NOT NULL,
    HoldExpiresAt datetime NOT NULL,
    IsDeleted boolean NOT NULL DEFAULT CAST(0 AS boolean),
    CreatedAt datetime NOT NULL,
    CreatedByUserId uuid NULL,
    UpdatedAt datetime NULL,
    UpdatedByUserId uuid NULL,
    varbinary(8) blob NOT NULL,
    CONSTRAINT PK_TripSeatHolds PRIMARY KEY (Id),
    CONSTRAINT CK_bus_TripSeatHolds_StopIndex CHECK (FromStopIndex < ToStopIndex),
    CONSTRAINT FK_TripSeatHolds_Seats_SeatId FOREIGN KEY (SeatId) REFERENCES fleet.Seats (Id) ON DELETE NO ACTION,
    CONSTRAINT FK_TripSeatHolds_TripStopTimes_FromTripStopTimeId FOREIGN KEY (FromTripStopTimeId) REFERENCES bus.TripStopTimes (Id) ON DELETE NO ACTION,
    CONSTRAINT FK_TripSeatHolds_TripStopTimes_ToTripStopTimeId FOREIGN KEY (ToTripStopTimeId) REFERENCES bus.TripStopTimes (Id) ON DELETE NO ACTION,
    CONSTRAINT FK_TripSeatHolds_Trips_TripId FOREIGN KEY (TripId) REFERENCES bus.Trips (Id) ON DELETE NO ACTION
);

CREATE TABLE bus.TripSegmentPrices (
    Id uuid NOT NULL,
    TenantId uuid NOT NULL,
    TripId uuid NOT NULL,
    FromTripStopTimeId uuid NOT NULL,
    ToTripStopTimeId uuid NOT NULL,
    FromStopIndex int NOT NULL,
    ToStopIndex int NOT NULL,
    CurrencyCode varchar(3) NOT NULL,
    BaseFare decimal(18,2) NOT NULL,
    TaxesFees decimal(18,2) NULL,
    TotalPrice decimal(18,2) NOT NULL,
    IsActive boolean NOT NULL DEFAULT CAST(1 AS boolean),
    IsDeleted boolean NOT NULL DEFAULT CAST(0 AS boolean),
    CreatedAt datetime NOT NULL,
    CreatedByUserId uuid NULL,
    UpdatedAt datetime NULL,
    UpdatedByUserId uuid NULL,
    varbinary(8) blob NOT NULL,
    CONSTRAINT PK_TripSegmentPrices PRIMARY KEY (Id),
    CONSTRAINT CK_bus_TripSegmentPrices_StopIndex CHECK (FromStopIndex < ToStopIndex),
    CONSTRAINT FK_TripSegmentPrices_TripStopTimes_FromTripStopTimeId FOREIGN KEY (FromTripStopTimeId) REFERENCES bus.TripStopTimes (Id) ON DELETE NO ACTION,
    CONSTRAINT FK_TripSegmentPrices_TripStopTimes_ToTripStopTimeId FOREIGN KEY (ToTripStopTimeId) REFERENCES bus.TripStopTimes (Id) ON DELETE NO ACTION,
    CONSTRAINT FK_TripSegmentPrices_Trips_TripId FOREIGN KEY (TripId) REFERENCES bus.Trips (Id) ON DELETE NO ACTION
);

CREATE TABLE bus.TripStopDropoffPoints (
    Id uuid NOT NULL,
    TenantId uuid NOT NULL,
    TripStopTimeId uuid NOT NULL,
    Name varchar(200) NOT NULL,
    AddressLine varchar(300) NULL,
    Latitude float NULL,
    Longitude float NULL,
    IsDefault boolean NOT NULL DEFAULT CAST(0 AS boolean),
    SortOrder int NOT NULL DEFAULT 0,
    IsActive boolean NOT NULL DEFAULT CAST(1 AS boolean),
    IsDeleted boolean NOT NULL DEFAULT CAST(0 AS boolean),
    CreatedAt datetime NOT NULL,
    CreatedByUserId uuid NULL,
    UpdatedAt datetime NULL,
    UpdatedByUserId uuid NULL,
    varbinary(8) blob NOT NULL,
    CONSTRAINT PK_TripStopDropoffPoints PRIMARY KEY (Id),
    CONSTRAINT FK_TripStopDropoffPoints_TripStopTimes_TripStopTimeId FOREIGN KEY (TripStopTimeId) REFERENCES bus.TripStopTimes (Id) ON DELETE NO ACTION
);

CREATE TABLE bus.TripStopPickupPoints (
    Id uuid NOT NULL,
    TenantId uuid NOT NULL,
    TripStopTimeId uuid NOT NULL,
    Name varchar(200) NOT NULL,
    AddressLine varchar(300) NULL,
    Latitude float NULL,
    Longitude float NULL,
    IsDefault boolean NOT NULL DEFAULT CAST(0 AS boolean),
    SortOrder int NOT NULL DEFAULT 0,
    IsActive boolean NOT NULL DEFAULT CAST(1 AS boolean),
    IsDeleted boolean NOT NULL DEFAULT CAST(0 AS boolean),
    CreatedAt datetime NOT NULL,
    CreatedByUserId uuid NULL,
    UpdatedAt datetime NULL,
    UpdatedByUserId uuid NULL,
    varbinary(8) blob NOT NULL,
    CONSTRAINT PK_TripStopPickupPoints PRIMARY KEY (Id),
    CONSTRAINT FK_TripStopPickupPoints_TripStopTimes_TripStopTimeId FOREIGN KEY (TripStopTimeId) REFERENCES bus.TripStopTimes (Id) ON DELETE NO ACTION
);

CREATE TABLE train.TrainCarSeats (
    Id uuid NOT NULL,
    TenantId uuid NOT NULL,
    CarId uuid NOT NULL,
    SeatNumber varchar(30) NOT NULL,
    SeatType int NOT NULL,
    CompartmentCode varchar(20) NULL,
    CompartmentIndex int NULL,
    RowIndex int NOT NULL,
    ColumnIndex int NOT NULL,
    IsWindow boolean NOT NULL,
    IsAisle boolean NOT NULL,
    SeatClass varchar(50) NULL,
    PriceModifier decimal(18,2) NULL,
    IsActive boolean NOT NULL DEFAULT CAST(1 AS boolean),
    IsDeleted boolean NOT NULL DEFAULT CAST(0 AS boolean),
    CreatedAt datetime NOT NULL,
    CreatedByUserId uuid NULL,
    UpdatedAt datetime NULL,
    UpdatedByUserId uuid NULL,
    varbinary(8) blob NOT NULL,
    CONSTRAINT PK_TrainCarSeats PRIMARY KEY (Id),
    CONSTRAINT FK_TrainCarSeats_TrainCars_CarId FOREIGN KEY (CarId) REFERENCES train.TrainCars (Id) ON DELETE NO ACTION
);

CREATE TABLE train.TripSegmentPrices (
    Id uuid NOT NULL,
    TenantId uuid NOT NULL,
    TripId uuid NOT NULL,
    FromTripStopTimeId uuid NOT NULL,
    ToTripStopTimeId uuid NOT NULL,
    FromStopIndex int NOT NULL,
    ToStopIndex int NOT NULL,
    CurrencyCode varchar(3) NOT NULL,
    BaseFare decimal(18,2) NOT NULL,
    TaxesFees decimal(18,2) NULL,
    TotalPrice decimal(18,2) NOT NULL,
    IsActive boolean NOT NULL DEFAULT CAST(1 AS boolean),
    IsDeleted boolean NOT NULL DEFAULT CAST(0 AS boolean),
    CreatedAt datetime NOT NULL,
    CreatedByUserId uuid NULL,
    UpdatedAt datetime NULL,
    UpdatedByUserId uuid NULL,
    varbinary(8) blob NOT NULL,
    CONSTRAINT PK_TripSegmentPrices PRIMARY KEY (Id),
    CONSTRAINT CK_train_TripSegmentPrices_StopIndex CHECK (FromStopIndex < ToStopIndex),
    CONSTRAINT FK_TripSegmentPrices_TripStopTimes_FromTripStopTimeId FOREIGN KEY (FromTripStopTimeId) REFERENCES train.TripStopTimes (Id) ON DELETE NO ACTION,
    CONSTRAINT FK_TripSegmentPrices_TripStopTimes_ToTripStopTimeId FOREIGN KEY (ToTripStopTimeId) REFERENCES train.TripStopTimes (Id) ON DELETE NO ACTION,
    CONSTRAINT FK_TripSegmentPrices_Trips_TripId FOREIGN KEY (TripId) REFERENCES train.Trips (Id) ON DELETE NO ACTION
);

CREATE TABLE train.TripSeatHolds (
    Id uuid NOT NULL,
    TenantId uuid NOT NULL,
    TripId uuid NOT NULL,
    TrainCarSeatId uuid NOT NULL,
    FromTripStopTimeId uuid NOT NULL,
    ToTripStopTimeId uuid NOT NULL,
    FromStopIndex int NOT NULL,
    ToStopIndex int NOT NULL,
    Status int NOT NULL,
    UserId uuid NULL,
    BookingId uuid NULL,
    HoldToken varchar(100) NOT NULL,
    HoldExpiresAt datetime NOT NULL,
    IsDeleted boolean NOT NULL DEFAULT CAST(0 AS boolean),
    CreatedAt datetime NOT NULL,
    CreatedByUserId uuid NULL,
    UpdatedAt datetime NULL,
    UpdatedByUserId uuid NULL,
    varbinary(8) blob NOT NULL,
    CONSTRAINT PK_TripSeatHolds PRIMARY KEY (Id),
    CONSTRAINT CK_train_TripSeatHolds_StopIndex CHECK (FromStopIndex < ToStopIndex),
    CONSTRAINT FK_TripSeatHolds_TrainCarSeats_TrainCarSeatId FOREIGN KEY (TrainCarSeatId) REFERENCES train.TrainCarSeats (Id) ON DELETE NO ACTION,
    CONSTRAINT FK_TripSeatHolds_TripStopTimes_FromTripStopTimeId FOREIGN KEY (FromTripStopTimeId) REFERENCES train.TripStopTimes (Id) ON DELETE NO ACTION,
    CONSTRAINT FK_TripSeatHolds_TripStopTimes_ToTripStopTimeId FOREIGN KEY (ToTripStopTimeId) REFERENCES train.TripStopTimes (Id) ON DELETE NO ACTION,
    CONSTRAINT FK_TripSeatHolds_Trips_TripId FOREIGN KEY (TripId) REFERENCES train.Trips (Id) ON DELETE NO ACTION
);
