import React,{useEffect,useMemo,useState}from 'react';
import {BarChart3,Loader2,RefreshCw} from 'lucide-react';
import {useSearchParams} from 'react-router-dom';
import TourManagementShell from '../components/TourManagementShell';
import {getManagerTourPackageReportingOverview,getManagerTourPackageReportingSourceBreakdown,listManagerTourPackageAuditEvents,listManagerTourPackages,listManagerTourSchedules,listManagerTours} from '../../../../services/tourService';
import {formatDateTime} from '../../../tours/utils/presentation';
import {updateSearchParams} from '../utils/options';

const isScalar=x=>['string','number','boolean'].includes(typeof x)||x===null;

export default function TourPackageReportingPage(){
const [sp,setSp]=useSearchParams();const [tours,setTours]=useState([]);const [packages,setPackages]=useState([]);const [schedules,setSchedules]=useState([]);const [overview,setOverview]=useState(null);const [breakdown,setBreakdown]=useState([]);const [events,setEvents]=useState([]);const [loading,setLoading]=useState(true);const [error,setError]=useState('');const [notice,setNotice]=useState('');
const tourId=sp.get('tourId')||'';const packageId=sp.get('packageId')||'';const scheduleId=sp.get('scheduleId')||'';const from=sp.get('from')||'';const to=sp.get('to')||'';
const selectedTour=useMemo(()=>tours.find(x=>x.id===tourId)||null,[tours,tourId]);
useEffect(()=>{(async()=>{try{const r=await listManagerTours({page:1,pageSize:100,includeDeleted:true});const next=r.items||[];setTours(next);if(!tourId&&next.length)updateSearchParams(setSp,{tourId:next[0].id});}catch(e){setError(e.message||'Không thể tải danh sách tour.');}})();},[]);
useEffect(()=>{if(!tourId)return;(async()=>{try{const [pr,sr]=await Promise.all([listManagerTourPackages(tourId,{page:1,pageSize:100,includeDeleted:true}),listManagerTourSchedules(tourId,{page:1,pageSize:100,includeDeleted:true})]);setPackages(pr.items||[]);setSchedules(sr.items||[]);}catch(e){setError(e.message||'Không thể tải bộ lọc báo cáo.');}})();},[tourId]);
useEffect(()=>{if(!tourId){setLoading(false);return;}load();},[tourId,packageId,scheduleId,from,to]);
async function load(){setLoading(true);setError('');setNotice('');try{const params={packageId:packageId||undefined,scheduleId:scheduleId||undefined,from:from||undefined,to:to||undefined,page:1,pageSize:100};const [o,b,e]=await Promise.all([getManagerTourPackageReportingOverview(tourId,params),getManagerTourPackageReportingSourceBreakdown(tourId,params),listManagerTourPackageAuditEvents(tourId,params)]);setOverview(o);setBreakdown(Array.isArray(b)?b:[]);setEvents(e.items||[]);}catch(err){setError(err.message||'Không thể tải báo cáo gói tour.');setOverview(null);setBreakdown([]);setEvents([]);}finally{setLoading(false);}}
const metrics=Object.entries(overview||{}).filter(([,v])=>isScalar(v)).slice(0,8);
return <TourManagementShell pageKey="reporting" title="Báo cáo gói tour" subtitle="Theo dõi số liệu kiểm toán, nguồn phát sinh và biến động cấu trúc gói theo từng tour." error={error} notice={notice} actions={<div className="flex flex-wrap items-center gap-3"><select value={tourId} onChange={e=>updateSearchParams(setSp,{tourId:e.target.value})} className="rounded-2xl border border-slate-200 bg-white px-4 py-3 text-sm font-bold text-slate-700 outline-none">{tours.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select><select value={packageId} onChange={e=>updateSearchParams(setSp,{packageId:e.target.value||''})} className="rounded-2xl border border-slate-200 bg-white px-4 py-3 text-sm font-bold text-slate-700 outline-none"><option value="">Tất cả gói</option>{packages.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select><select value={scheduleId} onChange={e=>updateSearchParams(setSp,{scheduleId:e.target.value||''})} className="rounded-2xl border border-slate-200 bg-white px-4 py-3 text-sm font-bold text-slate-700 outline-none"><option value="">Tất cả lịch</option>{schedules.map(x=><option key={x.id} value={x.id}>{x.code}</option>)}</select><input type="date" value={from} onChange={e=>updateSearchParams(setSp,{from:e.target.value||''})} className="rounded-2xl border border-slate-200 bg-white px-4 py-3 text-sm font-bold text-slate-700 outline-none"/><input type="date" value={to} onChange={e=>updateSearchParams(setSp,{to:e.target.value||''})} className="rounded-2xl border border-slate-200 bg-white px-4 py-3 text-sm font-bold text-slate-700 outline-none"/><button type="button" onClick={load} className="px-5 py-3 bg-slate-900 text-white rounded-2xl font-black text-xs uppercase tracking-widest flex items-center gap-2 shadow-sm"><RefreshCw size={14}/>Tải lại</button></div>}>
<div className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-4 gap-4">{loading?[1,2,3,4].map(x=><div key={x} className="bg-white rounded-[2rem] border border-slate-100 shadow-sm px-6 py-10 text-sm font-bold text-slate-400 flex items-center gap-3"><Loader2 size={16} className="animate-spin"/>Đang tải...</div>):metrics.length?metrics.map(([k,v])=><div key={k} className="bg-white rounded-[2rem] border border-slate-100 shadow-sm p-5"><p className="text-3xl font-black text-slate-900">{String(v??'--')}</p><p className="text-[10px] font-black uppercase tracking-widest text-slate-400 mt-1">{k}</p></div>):<div className="md:col-span-2 xl:col-span-4 bg-white rounded-[2rem] border border-slate-100 shadow-sm px-6 py-10 text-sm font-bold text-slate-400">Chưa có chỉ số tổng quan cho bộ lọc hiện tại.</div>}</div>
<div className="grid grid-cols-1 xl:grid-cols-[0.95fr,1.05fr] gap-6"><div className="bg-white rounded-[2.5rem] border border-slate-100 shadow-sm overflow-hidden"><div className="p-8 border-b border-slate-100"><h2 className="text-2xl font-black text-slate-900 tracking-tight flex items-center gap-3"><BarChart3 size={20}/>Phân rã theo nguồn</h2><p className="text-slate-500 font-medium mt-1">{selectedTour?`Tour đang xem: ${selectedTour.name}`:'Chọn tour để xem nguồn phát sinh.'}</p></div><div className="p-8 space-y-3">{loading?<div className="text-sm font-bold text-slate-400 flex items-center gap-3"><Loader2 size={16} className="animate-spin"/>Đang tải nguồn phát sinh...</div>:breakdown.length===0?<div className="text-sm font-bold text-slate-400">Chưa có dữ liệu breakdown.</div>:breakdown.map((item,index)=><div key={`${item.sourceType||'source'}-${index}`} className="rounded-2xl border border-slate-100 bg-slate-50 px-5 py-4"><div className="flex items-center justify-between gap-3"><div><p className="font-black text-slate-900">{item.sourceType||item.label||`Nguồn ${index+1}`}</p><p className="text-[10px] font-black uppercase tracking-widest text-slate-400 mt-1">{Object.entries(item).filter(([k,v])=>k!=='sourceType'&&isScalar(v)).map(([k,v])=>`${k}: ${v??'--'}`).join(' · ')}</p></div></div></div>)}</div></div><div className="bg-white rounded-[2.5rem] border border-slate-100 shadow-sm overflow-hidden"><div className="p-8 border-b border-slate-100"><h2 className="text-2xl font-black text-slate-900 tracking-tight">Nhật ký audit</h2><p className="text-slate-500 font-medium mt-1">Các sự kiện hệ thống ghi nhận cho package booking, reschedule, cancellation và override.</p></div><div className="p-8 space-y-3">{loading?<div className="text-sm font-bold text-slate-400 flex items-center gap-3"><Loader2 size={16} className="animate-spin"/>Đang tải audit events...</div>:events.length===0?<div className="text-sm font-bold text-slate-400">Chưa có sự kiện audit.</div>:events.map(event=><div key={event.id||`${event.eventType}-${event.occurredAt}`} className="rounded-2xl border border-slate-100 bg-slate-50 px-5 py-4"><div className="flex items-start justify-between gap-4"><div><p className="font-black text-slate-900">{event.title||event.eventType||'Audit event'}</p><p className="text-sm text-slate-500 font-medium mt-1">{event.description||event.notes||'Không có mô tả bổ sung.'}</p><p className="text-[10px] font-black uppercase tracking-widest text-slate-400 mt-2">{[event.severity,event.sourceType,event.actorDisplayName].filter(Boolean).join(' · ')}</p></div><div className="text-right shrink-0"><p className="text-xs font-black text-slate-700">{formatDateTime(event.occurredAt||event.createdAt)}</p></div></div></div>)}</div></div></div>
{overview&&<div className="bg-white rounded-[2.5rem] border border-slate-100 shadow-sm overflow-hidden"><div className="p-8 border-b border-slate-100"><h2 className="text-2xl font-black text-slate-900 tracking-tight">Payload tổng quan</h2><p className="text-slate-500 font-medium mt-1">Hiển thị đầy đủ dữ liệu trả về từ backend để đối chiếu nhanh khi kiểm thử.</p></div><div className="p-8"><pre className="rounded-[1.8rem] border border-slate-100 bg-slate-50 px-5 py-5 text-xs font-medium text-slate-700 overflow-x-auto whitespace-pre-wrap">{JSON.stringify(overview,null,2)}</pre></div></div>}
</TourManagementShell>;}
