/*
  Local defense reset for TicketBookingV3.

  Keeps:
  - dbo.AspNet* identity tables, admin/tenant accounts
  - auth.* permissions
  - tenants.* existing tenants and tenant memberships/roles
  - geo.* province/district/ward master data
  - dbo.__EFMigrationsHistory

  Clears:
  - public/domain/business data that is regenerated by application seeds
*/

SET NOCOUNT ON;
SET XACT_ABORT ON;
SET ANSI_NULLS ON;
SET ANSI_PADDING ON;
SET ANSI_WARNINGS ON;
SET ARITHABORT ON;
SET CONCAT_NULL_YIELDS_NULL ON;
SET QUOTED_IDENTIFIER ON;
SET NUMERIC_ROUNDABORT OFF;

DECLARE @TargetSchemas table ([Name] sysname PRIMARY KEY);
INSERT INTO @TargetSchemas ([Name])
VALUES
    (N'bus'),
    (N'catalog'),
    (N'cms'),
    (N'commerce'),
    (N'fleet'),
    (N'flight'),
    (N'hotels'),
    (N'tours'),
    (N'train');

DECLARE @sql nvarchar(max) = N'';

SELECT @sql = @sql + N'
ALTER TABLE ' + QUOTENAME(s.name) + N'.' + QUOTENAME(t.name) + N' NOCHECK CONSTRAINT ALL;'
FROM sys.tables t
JOIN sys.schemas s ON s.schema_id = t.schema_id
WHERE s.name IN (SELECT [Name] FROM @TargetSchemas);

SELECT @sql = @sql + N'
DELETE FROM ' + QUOTENAME(s.name) + N'.' + QUOTENAME(t.name) + N';'
FROM sys.tables t
JOIN sys.schemas s ON s.schema_id = t.schema_id
WHERE s.name IN (SELECT [Name] FROM @TargetSchemas)
ORDER BY s.name, t.name;

SELECT @sql = @sql + N'
ALTER TABLE ' + QUOTENAME(s.name) + N'.' + QUOTENAME(t.name) + N' WITH CHECK CHECK CONSTRAINT ALL;'
FROM sys.tables t
JOIN sys.schemas s ON s.schema_id = t.schema_id
WHERE s.name IN (SELECT [Name] FROM @TargetSchemas);

BEGIN TRANSACTION;
EXEC sys.sp_executesql @sql;
COMMIT TRANSACTION;

SELECT s.name AS SchemaName, t.name AS TableName, SUM(p.rows) AS [Rows]
FROM sys.tables t
JOIN sys.schemas s ON s.schema_id = t.schema_id
JOIN sys.partitions p ON p.object_id = t.object_id AND p.index_id IN (0, 1)
WHERE s.name IN (SELECT [Name] FROM @TargetSchemas)
GROUP BY s.name, t.name
ORDER BY s.name, t.name;
